export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role_key: string;
          employee_id: string | null;
          phone: string | null;
          avatar_url: string | null;
          department: string | null;
          college_id: string | null;
          status: string;
          two_factor_enabled: boolean;
          last_login_at: string | null;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          role_key?: string;
          employee_id?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          department?: string | null;
          college_id?: string | null;
          status?: string;
          two_factor_enabled?: boolean;
          last_login_at?: string | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role_key?: string;
          employee_id?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          department?: string | null;
          college_id?: string | null;
          status?: string;
          two_factor_enabled?: boolean;
          last_login_at?: string | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      colleges: {
        Row: {
          id: string;
          name: string;
          college_code: string;
          vtu_code: string | null;
          university_code: string | null;
          aishe_code: string | null;
          type: string;
          district: string;
          state: string;
          address: string | null;
          website: string | null;
          established_year: number | null;
          naac_grade: string | null;
          nba_status: string | null;
          tier: string;
          student_strength: number;
          eligible_students_count: number;
          branches_available: string[];
          training_mode: string;
          status: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          college_code: string;
          vtu_code?: string | null;
          university_code?: string | null;
          aishe_code?: string | null;
          type?: string;
          district: string;
          state?: string;
          address?: string | null;
          website?: string | null;
          established_year?: number | null;
          naac_grade?: string | null;
          nba_status?: string | null;
          tier?: string;
          student_strength?: number;
          eligible_students_count?: number;
          branches_available?: string[];
          training_mode?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          college_code?: string;
          vtu_code?: string | null;
          university_code?: string | null;
          aishe_code?: string | null;
          type?: string;
          district?: string;
          state?: string;
          address?: string | null;
          website?: string | null;
          established_year?: number | null;
          naac_grade?: string | null;
          nba_status?: string | null;
          tier?: string;
          student_strength?: number;
          eligible_students_count?: number;
          branches_available?: string[];
          training_mode?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      csr_drives: {
        Row: {
          id: string;
          drive_code: string;
          name: string;
          description: string | null;
          academic_year: string;
          batch: string;
          start_date: string;
          end_date: string;
          status: string;
          mode: string;
          min_aggregate: number;
          backlogs_allowed: number;
          branches_eligible: string[];
          target_registrations: number;
          target_selections: number;
          current_phase: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          drive_code: string;
          name: string;
          description?: string | null;
          academic_year?: string;
          batch?: string;
          start_date: string;
          end_date: string;
          status?: string;
          mode?: string;
          min_aggregate?: number;
          backlogs_allowed?: number;
          branches_eligible?: string[];
          target_registrations?: number;
          target_selections?: number;
          current_phase?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          drive_code?: string;
          name?: string;
          description?: string | null;
          academic_year?: string;
          batch?: string;
          start_date?: string;
          end_date?: string;
          status?: string;
          mode?: string;
          min_aggregate?: number;
          backlogs_allowed?: number;
          branches_eligible?: string[];
          target_registrations?: number;
          target_selections?: number;
          current_phase?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      students: {
        Row: {
          id: string;
          student_id: string;
          profile_id: string | null;
          full_name: string;
          email: string;
          mobile: string;
          whatsapp_number: string | null;
          gender: string;
          dob: string;
          college_id: string;
          college_name: string;
          usn: string;
          branch: string;
          degree: string;
          year_of_passing: number;
          semester: number;
          cgpa: number | null;
          percentage: number | null;
          backlogs_active: number;
          backlogs_history: number;
          aadhaar_last4: string | null;
          city: string;
          district: string;
          state: string;
          pincode: string | null;
          photo_url: string | null;
          resume_url: string | null;
          status: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          student_id: string;
          profile_id?: string | null;
          full_name: string;
          email: string;
          mobile: string;
          whatsapp_number?: string | null;
          gender: string;
          dob: string;
          college_id: string;
          college_name: string;
          usn: string;
          branch: string;
          degree?: string;
          year_of_passing?: number;
          semester?: number;
          cgpa?: number | null;
          percentage?: number | null;
          backlogs_active?: number;
          backlogs_history?: number;
          aadhaar_last4?: string | null;
          city: string;
          district: string;
          state?: string;
          pincode?: string | null;
          photo_url?: string | null;
          resume_url?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          student_id?: string;
          profile_id?: string | null;
          full_name?: string;
          email?: string;
          mobile?: string;
          whatsapp_number?: string | null;
          gender?: string;
          dob?: string;
          college_id?: string;
          college_name?: string;
          usn?: string;
          branch?: string;
          degree?: string;
          year_of_passing?: number;
          semester?: number;
          cgpa?: number | null;
          percentage?: number | null;
          backlogs_active?: number;
          backlogs_history?: number;
          aadhaar_last4?: string | null;
          city?: string;
          district?: string;
          state?: string;
          pincode?: string | null;
          photo_url?: string | null;
          resume_url?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      offer_letters: {
        Row: {
          id: string;
          offer_code: string;
          student_id: string;
          drive_id: string;
          college_id: string;
          template_id: string | null;
          candidate_name: string;
          candidate_email: string;
          candidate_phone: string;
          course_name: string;
          stipend_amount: number;
          training_location: string;
          issue_date: string;
          valid_until: string;
          status: string;
          pdf_url: string | null;
          qr_verification_code: string;
          accepted_at: string | null;
          acceptance_ip: string | null;
          digital_signature_hash: string | null;
          rejection_reason: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          offer_code: string;
          student_id: string;
          drive_id: string;
          college_id: string;
          template_id?: string | null;
          candidate_name: string;
          candidate_email: string;
          candidate_phone: string;
          course_name: string;
          stipend_amount: number;
          training_location?: string;
          issue_date?: string;
          valid_until: string;
          status?: string;
          pdf_url?: string | null;
          qr_verification_code: string;
          accepted_at?: string | null;
          acceptance_ip?: string | null;
          digital_signature_hash?: string | null;
          rejection_reason?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          offer_code?: string;
          student_id?: string;
          drive_id?: string;
          college_id?: string;
          template_id?: string | null;
          candidate_name?: string;
          candidate_email?: string;
          candidate_phone?: string;
          course_name?: string;
          stipend_amount?: number;
          training_location?: string;
          issue_date?: string;
          valid_until?: string;
          status?: string;
          pdf_url?: string | null;
          qr_verification_code?: string;
          accepted_at?: string | null;
          acceptance_ip?: string | null;
          digital_signature_hash?: string | null;
          rejection_reason?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      feature_flags: {
        Row: {
          id: string;
          flag_key: string;
          display_name: string;
          description: string | null;
          is_enabled: boolean;
          category: string;
          affected_portals: string[];
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          flag_key: string;
          display_name: string;
          description?: string | null;
          is_enabled?: boolean;
          category?: string;
          affected_portals?: string[];
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          flag_key?: string;
          display_name?: string;
          description?: string | null;
          is_enabled?: boolean;
          category?: string;
          affected_portals?: string[];
          updated_by?: string | null;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          user_email: string | null;
          user_role: string | null;
          module: string;
          action: string;
          resource_id: string | null;
          old_value: Json | null;
          new_value: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          user_email?: string | null;
          user_role?: string | null;
          module: string;
          action: string;
          resource_id?: string | null;
          old_value?: Json | null;
          new_value?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          user_email?: string | null;
          user_role?: string | null;
          module?: string;
          action?: string;
          resource_id?: string | null;
          old_value?: Json | null;
          new_value?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      selected_students_view: {
        Row: {
          student_id: string;
          student_code: string;
          full_name: string;
          email: string;
          mobile: string;
          college_name: string;
          district: string;
          branch: string;
          cgpa: number | null;
          drive_id: string;
          drive_name: string;
          course_allocated: string;
          selection_date: string;
          offer_code: string | null;
          offer_status: string | null;
          offer_pdf_url: string | null;
        };
      };
      qualified_students_view: {
        Row: {
          student_id: string;
          student_code: string;
          full_name: string;
          email: string;
          mobile: string;
          college_name: string;
          district: string;
          branch: string;
          exam_score: number;
          attempted: number;
          correct: number;
          evaluated_at: string;
          drive_id: string;
          drive_name: string;
          interview_status: string | null;
          interview_time: string | null;
        };
      };
      college_dashboard_view: {
        Row: {
          college_id: string;
          college_name: string;
          college_code: string;
          district: string;
          tier: string;
          total_registered: number;
          total_exam_passed: number;
          total_selected: number;
          total_offers_accepted: number;
        };
      };
      district_dashboard_view: {
        Row: {
          district_name: string;
          region: string;
          partner_colleges: number;
          registered_students: number;
          selected_students: number;
          avg_exam_score: number | null;
        };
      };
    };
    Functions: {
      generate_student_id: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      generate_offer_number: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      calculate_exam_score: {
        Args: {
          p_session_id: string;
        };
        Returns: Json;
      };
    };
  };
}
