const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');

const { getSupabaseCredentials } = require('./getEnv');
const { url, key } = getSupabaseCredentials();
const supabase = createClient(url, key);

const questionsData = [
  // SECTION A: APTITUDE (20 Questions)
  {
    id: "q-apt-01",
    category: "Aptitude",
    difficulty: "Easy",
    type: "MCQ",
    question: "What is 25% of 480?",
    options: ["100", "110", "120", "140"],
    correct_answer: 2,
    explanation: "25% of 480 = (25 / 100) * 480 = 120.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-02",
    category: "Aptitude",
    difficulty: "Medium",
    type: "MCQ",
    question: "Find the next number: 3, 8, 15, 24, 35, ?",
    options: ["42", "48", "50", "56"],
    correct_answer: 1,
    explanation: "The pattern is n^2 - 1 or consecutive odd differences (+5, +7, +9, +11, +13). 35 + 13 = 48.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-03",
    category: "Aptitude",
    difficulty: "Easy",
    type: "MCQ",
    question: "A train travels 360 km in 6 hours. Its speed is:",
    options: ["50 km/h", "60 km/h", "70 km/h", "80 km/h"],
    correct_answer: 1,
    explanation: "Speed = Distance / Time = 360 km / 6 h = 60 km/h.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-04",
    category: "Aptitude",
    difficulty: "Easy",
    type: "MCQ",
    question: "The average of 10, 20, 30, 40 and 50 is:",
    options: ["25", "30", "35", "40"],
    correct_answer: 1,
    explanation: "Average = (10 + 20 + 30 + 40 + 50) / 5 = 150 / 5 = 30.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-05",
    category: "Aptitude",
    difficulty: "Easy",
    type: "MCQ",
    question: "What is 18 × 17?",
    options: ["296", "306", "314", "326"],
    correct_answer: 1,
    explanation: "18 * 17 = 18 * (20 - 3) = 360 - 54 = 306.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-06",
    category: "Aptitude",
    difficulty: "Easy",
    type: "MCQ",
    question: "A shop gives 20% discount on ₹500. Selling price is:",
    options: ["₹350", "₹375", "₹400", "₹425"],
    correct_answer: 2,
    explanation: "Discount = 20% of 500 = ₹100. Selling price = 500 - 100 = ₹400.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-07",
    category: "Aptitude",
    difficulty: "Medium",
    type: "MCQ",
    question: "2, 6, 12, 20, 30, ?",
    options: ["40", "42", "44", "46"],
    correct_answer: 1,
    explanation: "Pattern: 1*2, 2*3, 3*4, 4*5, 5*6, 6*7 = 42 (differences: 4, 6, 8, 10, 12).",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-08",
    category: "Aptitude",
    difficulty: "Medium",
    type: "MCQ",
    question: "A man buys an item for ₹800 and sells for ₹920. Profit % =",
    options: ["10%", "12%", "15%", "18%"],
    correct_answer: 2,
    explanation: "Profit = 920 - 800 = 120. Profit % = (120 / 800) * 100 = 15%.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-09",
    category: "Aptitude",
    difficulty: "Easy",
    type: "MCQ",
    question: "The ratio 15:25 simplifies to:",
    options: ["2:3", "3:5", "5:7", "7:9"],
    correct_answer: 1,
    explanation: "15 / 25 simplifies by dividing by 5 to 3:5.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-10",
    category: "Aptitude",
    difficulty: "Medium",
    type: "MCQ",
    question: "Square root of 784 is:",
    options: ["26", "27", "28", "29"],
    correct_answer: 2,
    explanation: "28^2 = 784, so sqrt(784) = 28.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-11",
    category: "Aptitude",
    difficulty: "Medium",
    type: "MCQ",
    question: "If x = 12, y = 8, then x² − y² =",
    options: ["60", "72", "80", "88"],
    correct_answer: 2,
    explanation: "x^2 - y^2 = 144 - 64 = 80 (or (12+8)*(12-8) = 20*4 = 80).",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-12",
    category: "Aptitude",
    difficulty: "Medium",
    type: "MCQ",
    question: "Compound interest on ₹1000 at 10% for 2 years is:",
    options: ["₹200", "₹210", "₹220", "₹250"],
    correct_answer: 1,
    explanation: "Amount = 1000 * (1 + 0.10)^2 = 1210. CI = 1210 - 1000 = ₹210.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-13",
    category: "Aptitude",
    difficulty: "Easy",
    type: "MCQ",
    question: "Find 35% of 600.",
    options: ["180", "190", "200", "210"],
    correct_answer: 3,
    explanation: "35% of 600 = 0.35 * 600 = 210.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-14",
    category: "Aptitude",
    difficulty: "Easy",
    type: "MCQ",
    question: "144 ÷ 12 × 5 =",
    options: ["50", "55", "60", "65"],
    correct_answer: 2,
    explanation: "Following BODMAS: 144 / 12 = 12. 12 * 5 = 60.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-15",
    category: "Aptitude",
    difficulty: "Easy",
    type: "MCQ",
    question: "The LCM of 12 and 18 is:",
    options: ["24", "30", "36", "48"],
    correct_answer: 2,
    explanation: "12 = 2^2 * 3, 18 = 2 * 3^2. LCM = 2^2 * 3^2 = 4 * 9 = 36.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-16",
    category: "Aptitude",
    difficulty: "Easy",
    type: "MCQ",
    question: "The HCF of 24 and 36 is:",
    options: ["6", "8", "12", "18"],
    correct_answer: 2,
    explanation: "24 = 12 * 2, 36 = 12 * 3. Highest Common Factor is 12.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-17",
    category: "Aptitude",
    difficulty: "Easy",
    type: "MCQ",
    question: "A car covers 240 km using 20 L petrol. Mileage =",
    options: ["10 km/L", "12 km/L", "14 km/L", "16 km/L"],
    correct_answer: 1,
    explanation: "Mileage = 240 km / 20 L = 12 km/L.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-18",
    category: "Aptitude",
    difficulty: "Easy",
    type: "MCQ",
    question: "5⁴ equals:",
    options: ["525", "625", "725", "825"],
    correct_answer: 1,
    explanation: "5^4 = 5 * 5 * 5 * 5 = 25 * 25 = 625.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-19",
    category: "Aptitude",
    difficulty: "Medium",
    type: "MCQ",
    question: "45% of a number is 90. The number is:",
    options: ["180", "190", "200", "220"],
    correct_answer: 2,
    explanation: "0.45 * x = 90 => x = 90 / 0.45 = 200.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-apt-20",
    category: "Aptitude",
    difficulty: "Medium",
    type: "MCQ",
    question: "If 8 workers finish a job in 12 days, 16 workers take:",
    options: ["4 days", "5 days", "6 days", "8 days"],
    correct_answer: 2,
    explanation: "Worker-days = 8 * 12 = 96. With 16 workers, days = 96 / 16 = 6 days.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },

  // SECTION B: REASONING (10 Questions)
  {
    id: "q-reas-01",
    category: "Reasoning",
    difficulty: "Easy",
    type: "MCQ",
    question: "Find the odd one out.",
    options: ["Rose", "Lotus", "Lily", "Mango"],
    correct_answer: 3,
    explanation: "Rose, Lotus, and Lily are flowers, whereas Mango is a fruit.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-reas-02",
    category: "Reasoning",
    difficulty: "Easy",
    type: "MCQ",
    question: "CAT : KITTEN :: DOG : ?",
    options: ["Cub", "Puppy", "Calf", "Kid"],
    correct_answer: 1,
    explanation: "A kitten is the offspring of a cat; a puppy is the offspring of a dog.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-reas-03",
    category: "Reasoning",
    difficulty: "Medium",
    type: "MCQ",
    question: "Complete the series: A, C, F, J, O, ?",
    options: ["T", "U", "V", "W"],
    correct_answer: 1,
    explanation: "Positions: A(1) + 2 = C(3); C(3) + 3 = F(6); F(6) + 4 = J(10); J(10) + 5 = O(15); O(15) + 6 = U(21).",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-reas-04",
    category: "Reasoning",
    difficulty: "Easy",
    type: "MCQ",
    question: "If SOUTH = HTUOS, then TRAIN = ?",
    options: ["NIART", "TRANI", "RAINT", "NIRAT"],
    correct_answer: 0,
    explanation: "The letters of the word are reversed. Reverse of TRAIN is NIART.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-reas-05",
    category: "Reasoning",
    difficulty: "Medium",
    type: "MCQ",
    question: "Which number replaces ? 2, 6, 12, 20, 30, ?",
    options: ["38", "40", "42", "44"],
    correct_answer: 2,
    explanation: "Differences are +4, +6, +8, +10, +12. 30 + 12 = 42.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-reas-06",
    category: "Reasoning",
    difficulty: "Medium",
    type: "MCQ",
    question: 'Pointing to a woman, Ravi says, "She is my mother\'s only daughter." The woman is Ravi\'s:',
    options: ["Sister", "Mother", "Wife", "Daughter"],
    correct_answer: 0,
    explanation: "Ravi's mother's only daughter is Ravi's sister.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-reas-07",
    category: "Reasoning",
    difficulty: "Easy",
    type: "MCQ",
    question: "If BOOK is coded as CPPL, then PEN is coded as:",
    options: ["QFO", "PEO", "QEN", "RFO"],
    correct_answer: 0,
    explanation: "Each letter is shifted by +1: P+1 = Q, E+1 = F, N+1 = O -> QFO.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-reas-08",
    category: "Reasoning",
    difficulty: "Medium",
    type: "MCQ",
    question: "Find the missing letter: B, D, G, K, ?",
    options: ["N", "O", "P", "Q"],
    correct_answer: 2,
    explanation: "Positions: B(2) + 2 = D(4); D(4) + 3 = G(7); G(7) + 4 = K(11); K(11) + 5 = P(16).",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-reas-09",
    category: "Reasoning",
    difficulty: "Medium",
    type: "MCQ",
    question: "Mirror image of 27 is:",
    options: ["72", "27", "L2", "Depends on mirror"],
    correct_answer: 3,
    explanation: "The reflection depends on whether the mirror is placed vertically (left/right) or horizontally (top/bottom).",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-reas-10",
    category: "Reasoning",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which shape has the maximum number of sides?",
    options: ["Pentagon", "Hexagon", "Octagon", "Decagon"],
    correct_answer: 3,
    explanation: "Decagon has 10 sides, Octagon has 8, Hexagon has 6, Pentagon has 5.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },

  // PROGRAMMING MCQS (30 Questions)
  {
    id: "q-prog-01",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which function is used to print output in C?",
    options: ["scanf()", "printf()", "gets()", "put()"],
    correct_answer: 1,
    explanation: "printf() prints formatted output to stdout in C.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-02",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which header file contains printf()?",
    options: ["math.h", "string.h", "stdio.h", "stdlib.h"],
    correct_answer: 2,
    explanation: "stdio.h (Standard Input Output) declares standard I/O functions including printf.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-03",
    category: "Programming",
    difficulty: "Medium",
    type: "MCQ",
    question: "What is the default value of an uninitialized local variable in C?",
    options: ["0", "NULL", "Garbage value", "1"],
    correct_answer: 2,
    explanation: "In C, automatic (local) variables contain garbage values unless explicitly initialized.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-04",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which data type stores a single character?",
    options: ["int", "char", "float", "string"],
    correct_answer: 1,
    explanation: "The char data type is used to store a single 1-byte character.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-05",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which operator is used to find the remainder?",
    options: ["/", "%", "*", "//"],
    correct_answer: 1,
    explanation: "The modulus operator (%) returns the remainder of integer division.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-06",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Array indexing in C starts from:",
    options: ["0", "1", "-1", "2"],
    correct_answer: 0,
    explanation: "C uses zero-based array indexing, so the first element is at index 0.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-07",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which loop executes at least once?",
    options: ["for", "while", "do-while", "foreach"],
    correct_answer: 2,
    explanation: "do-while checks its condition at the bottom, so it always executes at least once.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-08",
    category: "Programming",
    difficulty: "Medium",
    type: "Code Snippet",
    question: "What is the output of the following C code?",
    code_snippet: "int a = 5;\nprintf(\"%d\", a++);",
    options: ["5", "6", "Error", "4"],
    correct_answer: 0,
    explanation: "Post-increment (a++) evaluates to the current value (5) before incrementing to 6.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-09",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which keyword is used to stop a loop?",
    options: ["exit", "stop", "break", "continue"],
    correct_answer: 2,
    explanation: "The break statement terminates execution of the nearest enclosing loop or switch.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-10",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which is a valid variable name?",
    options: ["2value", "value_2", "float", "#num"],
    correct_answer: 1,
    explanation: "Variable names cannot start with a digit, cannot use special symbols like #, and cannot be keywords like float.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-11",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Java is primarily a ______ language.",
    options: ["Procedural", "Object-Oriented", "Functional", "Machine"],
    correct_answer: 1,
    explanation: "Java is fundamentally an Object-Oriented Programming (OOP) language.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-12",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which method is the entry point of a Java program?",
    options: ["start()", "run()", "main()", "init()"],
    correct_answer: 2,
    explanation: "public static void main(String[] args) is the predefined entry point invoked by JVM.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-13",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which keyword creates an object in Java?",
    options: ["object", "new", "class", "create"],
    correct_answer: 1,
    explanation: "The 'new' keyword dynamically allocates memory on the heap for a new object.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-14",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which package is imported automatically?",
    options: ["java.util", "java.io", "java.lang", "java.sql"],
    correct_answer: 2,
    explanation: "java.lang is implicitly imported into every Java compilation unit by the compiler.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-15",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which keyword is used to inherit a class?",
    options: ["implement", "inherits", "extends", "using"],
    correct_answer: 2,
    explanation: "The 'extends' keyword establishes class inheritance in Java.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-16",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which keyword refers to the current object?",
    options: ["self", "this", "super", "current"],
    correct_answer: 1,
    explanation: "'this' represents the reference variable that points to the current object.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-17",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which access modifier is visible everywhere?",
    options: ["private", "protected", "default", "public"],
    correct_answer: 3,
    explanation: "'public' members are accessible from any class in any package.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-18",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "JVM stands for:",
    options: ["Java Variable Machine", "Java Virtual Machine", "Java Visual Method", "Joint Virtual Machine"],
    correct_answer: 1,
    explanation: "JVM stands for Java Virtual Machine, the runtime execution engine.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-19",
    category: "Programming",
    difficulty: "Medium",
    type: "MCQ",
    question: "Which interface is used for multithreading?",
    options: ["Thread", "Runnable", "Process", "Executor"],
    correct_answer: 1,
    explanation: "java.lang.Runnable is the primary functional interface intended for thread execution.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-20",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which keyword is used for exception handling?",
    options: ["try", "catch", "finally", "All of these"],
    correct_answer: 3,
    explanation: "try, catch, and finally are all core keywords used for structured exception handling.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-21",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which SQL statement retrieves data?",
    options: ["INSERT", "UPDATE", "SELECT", "DELETE"],
    correct_answer: 2,
    explanation: "SELECT queries and retrieves data records from relational database tables.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-22",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which SQL clause filters rows?",
    options: ["GROUP BY", "ORDER BY", "WHERE", "HAVING"],
    correct_answer: 2,
    explanation: "WHERE specifies row-level conditional filters on SELECT, UPDATE, and DELETE operations.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-23",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which command adds a new row to a table?",
    options: ["CREATE", "INSERT", "ALTER", "MODIFY"],
    correct_answer: 1,
    explanation: "INSERT INTO table_name VALUES (...) appends new tuples to a table.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-24",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "HTML stands for:",
    options: ["Hyper Text Markup Language", "High Text Machine Language", "Hyper Transfer Markup Language", "Hyper Tool Multi Language"],
    correct_answer: 0,
    explanation: "HTML stands for HyperText Markup Language, the standard markup language for web documents.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-25",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which HTML tag creates a hyperlink?",
    options: ["<link>", "<href>", "<a>", "<url>"],
    correct_answer: 2,
    explanation: "The anchor tag <a> with href attribute creates clickable hyperlinks.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-26",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which CSS property changes text color?",
    options: ["font-color", "text-color", "color", "background"],
    correct_answer: 2,
    explanation: "The 'color' property in CSS specifies foreground text color.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-27",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which symbol is used for comments in C?",
    options: ["<!-- -->", "//", "##", "**"],
    correct_answer: 1,
    explanation: "// introduces a single-line comment in C99 and modern C.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-28",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Which data structure follows FIFO?",
    options: ["Stack", "Queue", "Tree", "Graph"],
    correct_answer: 1,
    explanation: "Queue follows First-In, First-Out (FIFO) ordering.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-29",
    category: "Programming",
    difficulty: "Medium",
    type: "MCQ",
    question: "Which searching algorithm works on sorted arrays?",
    options: ["Linear Search", "Binary Search", "DFS", "BFS"],
    correct_answer: 1,
    explanation: "Binary Search operates in O(log n) time by repeatedly halving search intervals on sorted data.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  },
  {
    id: "q-prog-30",
    category: "Programming",
    difficulty: "Easy",
    type: "MCQ",
    question: "Git is mainly used for:",
    options: ["Image Editing", "Database Design", "Version Control", "Web Hosting"],
    correct_answer: 2,
    explanation: "Git is a distributed version control system for tracking changes in source code.",
    marks: 1,
    negative_marks: 0.0,
    is_active: true
  }
];

async function seed() {
  console.log(`Seeding ${questionsData.length} exam questions...`);
  // Clean existing questions to prevent duplicates
  const { error: delError } = await supabase.from('questions').delete().neq('id', 'non-existent');
  if (delError) console.warn('Delete warning:', delError.message);

  // Insert in batches of 15
  for (let i = 0; i < questionsData.length; i += 15) {
    const chunk = questionsData.slice(i, i + 15);
    const { data, error } = await supabase.from('questions').upsert(chunk).select();
    if (error) {
      console.error(`Error inserting chunk ${i / 15}:`, error.message);
    } else {
      console.log(`Inserted questions ${i + 1} to ${i + chunk.length}`);
    }
  }

  const { count } = await supabase.from('questions').select('*', { count: 'exact', head: true });
  console.log(`Verification: Total questions in database = ${count}`);
}

seed();
