# Generated by Django 6.1.1 on 2026-09-28 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drives', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('Technical', 'Technical Interview (Coding & Systems)'), ('HR', 'HR & Cultural Fit Round'), ('Management', 'Executive Leadership Round')], default='Technical', max_length=50)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_rounds', to='drives.csrdrive')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panelist_name', models.CharField(max_length=150)),
                ('panelist_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('interview_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Rescheduled', 'Rescheduled'), ('Cancelled', 'Cancelled'), ('No_Show', 'Candidate No-Show')], default='Scheduled', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='interviews.interviewround')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.PositiveSmallIntegerField(default=7)),
                ('communication_score', models.PositiveSmallIntegerField(default=8)),
                ('problem_solving_score', models.PositiveSmallIntegerField(default=7)),
                ('attitude_culture_score', models.PositiveSmallIntegerField(default=8)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('areas_for_improvement', models.TextField(blank=True, null=True)),
                ('final_decision', models.CharField(choices=[('Select', 'Select / Recommend Next Round'), ('Reject', 'Reject'), ('Hold', 'Keep on Hold')], default='Select', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='interviews.interviewschedule')),
            ],
        ),
    ]
