# Generated by Django 6.1.1 on 2026-09-28 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSRDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Registration', 'Registration Active'), ('Assessment', 'Online Assessment'), ('Interview', 'Interviews & Evaluations'), ('Completed', 'Completed / Archived')], default='Registration', max_length=30)),
                ('target_districts', models.JSONField(blank=True, default=list)),
                ('total_intake', models.PositiveIntegerField(default=500)),
                ('budget', models.DecimalField(decimal_places=2, default=1500000.0, max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeDriveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('quota', models.PositiveIntegerField(default=100)),
                ('registered_count', models.PositiveIntegerField(default=0)),
                ('shortlisted_count', models.PositiveIntegerField(default=0)),
                ('placed_count', models.PositiveIntegerField(default=0)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='drives.csrdrive')),
            ],
        ),
        migrations.CreateModel(
            name='DrivePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], default='Pending', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='drives.csrdrive')),
            ],
            options={
                'ordering': ['phase_number'],
            },
        ),
    ]
