import {
  PlatformBrandingSettings,
  AcademicYearRecord,
  SecurityActiveSession,
  SecurityLoginEvent,
  StorageBucketStat,
  StorageFileItem,
  SystemBackupRecord,
  FeatureFlagItem,
  SystemHealthMetric,
  IntegrationConfig,
  AdminErrorLog,
} from '@/types';

// ==========================================
// 1. GQT BRANDING & PLATFORM THEME CONFIG
// ==========================================
export const DEFAULT_BRANDING_SETTINGS: PlatformBrandingSettings = {
  platformName: 'Global Quest Technologies CSR Platform',
  organizationName: 'Global Quest Technologies Pvt. Ltd.',
  tagline: 'Bridging Academia and Enterprise via AI-First CSR Recruitment',
  lightLogoUrl: '/images/brand/gqt-logo-light.svg',
  darkLogoUrl: '/images/brand/gqt-logo-dark.svg',
  faviconUrl: '/favicon.ico',
  primaryColor: '#001B4D',
  secondaryColor: '#005BBB',
  accentColor: '#14B8FF',
  fontFamily: 'Inter, system-ui, sans-serif',
  footerText: '© 2026 Global Quest Technologies. All Rights Reserved. Official CSR Drive Governance Engine.',
  supportEmail: '[EMAIL_ADDRESS]',
  supportPhone: '+91 9964156024',
  websiteUrl: 'https://globalquesttechnologies.com',
  socialLinks: {
    linkedin: 'https://linkedin.com/company/global-quest-technologies',
    twitter: 'https://twitter.com/GlobalQuestTech',
    youtube: 'https://youtube.com/@GlobalQuestTech',
    github: 'https://github.com/GlobalQuestTech',
  },
};

// ==========================================
// 2. ACADEMIC YEARS
// ==========================================
export const ACADEMIC_YEARS: AcademicYearRecord[] = [
  {
    id: 'ay-2026-27',
    year: '2026-27',
    startDate: '2026-06-01',
    endDate: '2027-05-31',
    status: 'Current',
    drivesCount: 14,
    collegesCount: 114,
    studentsCount: 21850,
    isLocked: false,
  },
  {
    id: 'ay-2027-28',
    year: '2027-28',
    startDate: '2027-06-01',
    endDate: '2028-05-31',
    status: 'Upcoming',
    drivesCount: 2,
    collegesCount: 38,
    studentsCount: 0,
    isLocked: false,
  },
  {
    id: 'ay-2025-26',
    year: '2025-26',
    startDate: '2025-06-01',
    endDate: '2026-05-31',
    status: 'Archived',
    drivesCount: 12,
    collegesCount: 96,
    studentsCount: 18420,
    isLocked: true,
  },
  {
    id: 'ay-2024-25',
    year: '2024-25',
    startDate: '2024-06-01',
    endDate: '2025-05-31',
    status: 'Archived',
    drivesCount: 8,
    collegesCount: 65,
    studentsCount: 12100,
    isLocked: true,
  },
];

// ==========================================
// 3. GLOBAL FEATURE FLAGS
// ==========================================
export const INITIAL_FEATURE_FLAGS: FeatureFlagItem[] = [
  {
    id: 'flag-exam',
    key: 'ENABLE_ONLINE_EXAMINATION',
    name: 'Online Assessment & Proctoring Engine',
    description: 'Enables live examination, camera/screen AI proctoring, and automatic scoring.',
    category: 'Core Modules',
    isEnabled: true,
    affectsPortals: ['student', 'hr', 'super_admin'],
    updatedAt: '2026-09-24T10:00:00Z',
    updatedBy: 'G.R Narendra Reddy',
  },
  {
    id: 'flag-interview',
    key: 'ENABLE_HR_INTERVIEW_WORKSPACE',
    name: 'HR Interview Scheduling & Evaluation',
    description: 'Enables video/in-person interview slotting, scorecard rubrics, and selection marking.',
    category: 'Core Modules',
    isEnabled: true,
    affectsPortals: ['hr', 'student', 'super_admin'],
    updatedAt: '2026-09-24T10:00:00Z',
    updatedBy: 'G.R Narendra Reddy',
  },
  {
    id: 'flag-offers',
    key: 'ENABLE_OFFER_LETTER_AUTOMATION',
    name: 'Offer Letter Generation & Digital Signing',
    description: 'Generates secure PDF LOIs, QR verification codes, and candidate signing flow.',
    category: 'Core Modules',
    isEnabled: true,
    affectsPortals: ['hr', 'student', 'admission_team', 'super_admin'],
    updatedAt: '2026-09-24T10:00:00Z',
    updatedBy: 'G.R Narendra Reddy',
  },
  {
    id: 'flag-whatsapp',
    key: 'ENABLE_WHATSAPP_AUTOMATION',
    name: 'WhatsApp Cloud API Outreach & Groups',
    description: 'Enables automatic Meta Cloud API template messaging and TPO drive group metadata creation.',
    category: 'Integrations',
    isEnabled: true,
    affectsPortals: ['hr', 'super_admin'],
    updatedAt: '2026-09-24T10:00:00Z',
    updatedBy: 'G.R Narendra Reddy',
  },
  {
    id: 'flag-email',
    key: 'ENABLE_HTML_EMAIL_ENGINE',
    name: 'Corporate HTML Email Broadcast Engine',
    description: 'Enables high-deliverability SMTP broadcasts, open tracking, and LOI release notices.',
    category: 'Integrations',
    isEnabled: true,
    affectsPortals: ['hr', 'super_admin'],
    updatedAt: '2026-09-24T10:00:00Z',
    updatedBy: 'G.R Narendra Reddy',
  },
  {
    id: 'flag-notifications',
    key: 'ENABLE_GLOBAL_NOTIFICATIONS',
    name: 'Realtime Omnichannel Notification Drawer',
    description: 'Push notifications via Supabase Realtime across all 8 sub-portals.',
    category: 'Core Modules',
    isEnabled: true,
    affectsPortals: ['all'],
    updatedAt: '2026-09-24T10:00:00Z',
    updatedBy: 'G.R Narendra Reddy',
  },
  {
    id: 'flag-certificates',
    key: 'ENABLE_DIGITAL_CERTIFICATES',
    name: 'CSR Participation & Qualification Certificates',
    description: 'Issues cryptographic completion certificates for qualified candidates.',
    category: 'Core Modules',
    isEnabled: true,
    affectsPortals: ['student', 'pto', 'super_admin'],
    updatedAt: '2026-09-24T10:00:00Z',
    updatedBy: 'G.R Narendra Reddy',
  },
  {
    id: 'flag-support',
    key: 'ENABLE_TICKET_HELPDESK',
    name: 'Integrated Candidate & TPO Support Chat',
    description: 'Enables live ticketing and support queries for candidates during drive execution.',
    category: 'Core Modules',
    isEnabled: true,
    affectsPortals: ['student', 'pto', 'super_admin'],
    updatedAt: '2026-09-24T10:00:00Z',
    updatedBy: 'G.R Narendra Reddy',
  },
  {
    id: 'flag-analytics',
    key: 'ENABLE_EXECUTIVE_BI_DASHBOARD',
    name: 'Executive Management BI & Karnataka Map',
    description: 'Power BI-grade analytics portal for Directors and Founders.',
    category: 'Security & Access',
    isEnabled: true,
    affectsPortals: ['management', 'super_admin'],
    updatedAt: '2026-09-24T10:00:00Z',
    updatedBy: 'G.R Narendra Reddy',
  },
  {
    id: 'flag-realtime',
    key: 'ENABLE_SUPABASE_REALTIME',
    name: 'Supabase Realtime WebSockets',
    description: 'Broadcasting live counter pulses, assessment war-room telemetry, and chat queues.',
    category: 'Integrations',
    isEnabled: true,
    affectsPortals: ['all'],
    updatedAt: '2026-09-24T10:00:00Z',
    updatedBy: 'G.R Narendra Reddy',
  },
  {
    id: 'flag-dark-mode',
    key: 'ENABLE_DARK_MODE_THEME',
    name: 'Adaptive Dark & Light Theme System',
    description: 'Allows portal users to toggle between Slate Dark Mode and Enterprise Light Theme.',
    category: 'UI & Experience',
    isEnabled: true,
    affectsPortals: ['all'],
    updatedAt: '2026-09-24T10:00:00Z',
    updatedBy: 'G.R Narendra Reddy',
  },
  {
    id: 'flag-maintenance',
    key: 'ENABLE_MAINTENANCE_BANNER',
    name: 'Global Maintenance Alert Banner',
    description: 'Displays scheduled system optimization alert at the top of all sub-portals.',
    category: 'Security & Access',
    isEnabled: false,
    affectsPortals: ['all'],
    updatedAt: '2026-09-24T10:00:00Z',
    updatedBy: 'G.R Narendra Reddy',
  },
];

// ==========================================
// 4. STORAGE BUCKETS & STATISTICS
// ==========================================
export const STORAGE_BUCKETS: StorageBucketStat[] = [
  {
    id: 'bkt-resumes',
    name: 'student-resumes',
    description: 'Uploaded candidate resumes (PDF/DOCX)',
    isPrivate: true,
    filesCount: 19420,
    totalSizeBytes: 38400000000,
    formattedSize: '35.8 GB',
    lastUpload: '2 mins ago',
    allowedMimeTypes: ['application/pdf', 'application/msword'],
  },
  {
    id: 'bkt-photos',
    name: 'student-photos',
    description: 'ID verification profile headshots',
    isPrivate: false,
    filesCount: 21850,
    totalSizeBytes: 14200000000,
    formattedSize: '13.2 GB',
    lastUpload: 'Just now',
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
  },
  {
    id: 'bkt-offers',
    name: 'offer-letters',
    description: 'Digitally signed LOI contract documents',
    isPrivate: true,
    filesCount: 4500,
    totalSizeBytes: 9800000000,
    formattedSize: '9.1 GB',
    lastUpload: '10 mins ago',
    allowedMimeTypes: ['application/pdf'],
  },
  {
    id: 'bkt-questions',
    name: 'question-images',
    description: 'Diagrams, circuit schematics, and code assets for Question Bank',
    isPrivate: false,
    filesCount: 1240,
    totalSizeBytes: 2400000000,
    formattedSize: '2.2 GB',
    lastUpload: '2 days ago',
    allowedMimeTypes: ['image/png', 'image/jpeg', 'image/svg+xml'],
  },
  {
    id: 'bkt-announcements',
    name: 'announcement-assets',
    description: 'Banners, flyers, and circulars for state-wide broadcasting',
    isPrivate: false,
    filesCount: 340,
    totalSizeBytes: 1100000000,
    formattedSize: '1.0 GB',
    lastUpload: '4 hours ago',
    allowedMimeTypes: ['image/jpeg', 'image/png', 'application/pdf'],
  },
  {
    id: 'bkt-certificates',
    name: 'certificates',
    description: 'Cryptographically signed qualification credentials',
    isPrivate: true,
    filesCount: 11220,
    totalSizeBytes: 16800000000,
    formattedSize: '15.6 GB',
    lastUpload: '1 hour ago',
    allowedMimeTypes: ['application/pdf'],
  },
  {
    id: 'bkt-documents',
    name: 'documents',
    description: 'Institutional MoUs, syllabi, college schedules, and circulars',
    isPrivate: true,
    filesCount: 820,
    totalSizeBytes: 4200000000,
    formattedSize: '3.9 GB',
    lastUpload: '1 day ago',
    allowedMimeTypes: ['application/pdf', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
  },
  {
    id: 'bkt-recordings',
    name: 'call-recordings',
    description: 'Institutional phone logs & audio recordings for quality audit',
    isPrivate: true,
    filesCount: 1840,
    totalSizeBytes: 42800000000,
    formattedSize: '39.8 GB',
    lastUpload: '35 mins ago',
    allowedMimeTypes: ['audio/mpeg', 'audio/wav', 'audio/mp4'],
  },
];

export const MOCK_STORAGE_FILES: StorageFileItem[] = [
  { id: 'fil-01', bucket: 'student-resumes', name: 'Aditi_Rao_RVCE_Resume_2026.pdf', size: '1.4 MB', sizeBytes: 1468000, mimeType: 'application/pdf', uploadedAt: '2026-09-24T18:12:00Z', uploadedBy: 'Aditi Rao', url: '/storage/student-resumes/Aditi_Rao_RVCE_Resume_2026.pdf' },
  { id: 'fil-02', bucket: 'offer-letters', name: 'GQT_OFFER_2026_001_Signed.pdf', size: '2.1 MB', sizeBytes: 2200000, mimeType: 'application/pdf', uploadedAt: '2026-09-24T19:30:00Z', uploadedBy: 'Aditi Rao', url: '/storage/offer-letters/GQT_OFFER_2026_001_Signed.pdf' },
  { id: 'fil-03', bucket: 'documents', name: 'RVCE_GQT_CSR_MoU_Executed_2026.pdf', size: '3.8 MB', sizeBytes: 3980000, mimeType: 'application/pdf', uploadedAt: '2026-05-15T11:00:00Z', uploadedBy: 'Kiran (CSR Manager)', url: '/storage/documents/RVCE_GQT_CSR_MoU_Executed_2026.pdf' },
  { id: 'fil-04', bucket: 'question-images', name: 'virtual_thread_scheduler_diagram.png', size: '480 KB', sizeBytes: 491000, mimeType: 'image/png', uploadedAt: '2026-08-10T14:20:00Z', uploadedBy: 'Super Admin', url: '/storage/question-images/virtual_thread_scheduler_diagram.png' },
  { id: 'fil-05', bucket: 'call-recordings', name: 'RVCE_TPO_Discussion_20260920.mp3', size: '8.4 MB', sizeBytes: 8800000, mimeType: 'audio/mpeg', uploadedAt: '2026-09-20T15:30:00Z', uploadedBy: 'Hitha, Kusuma', url: '/storage/call-recordings/RVCE_TPO_Discussion_20260920.mp3' },
];

// ==========================================
// 5. SECURITY CENTER & ACTIVE SESSIONS
// ==========================================
export const ACTIVE_SESSIONS: SecurityActiveSession[] = [
  {
    id: 'ses-001',
    userId: 'usr-admin-01',
    userName: 'G.R Narendra Reddy',
    userEmail: '[EMAIL_ADDRESS]',
    role: 'super_admin',
    device: 'Laptop',
    browser: 'Chrome 128 / Windows 11 Pro',
    os: 'Windows 11',
    ipAddress: '115.112.82.14',
    location: 'Bengaluru, Karnataka (GQT HQ)',
    loginTime: '2026-09-25T08:00:00Z',
    lastActive: 'Just now',
    isCurrentSession: true,
    isTrusted: true,
  },
  {
    id: 'ses-002',
    userId: 'usr-csr-01',
    userName: 'Kiran',
    userEmail: '[EMAIL_ADDRESS]',
    role: 'csr_manager',
    device: 'Laptop',
    browser: 'Firefox 129 / macOS Sequoia',
    os: 'macOS',
    ipAddress: '115.112.82.19',
    location: 'Bengaluru, Karnataka',
    loginTime: '2026-09-25T08:30:00Z',
    lastActive: '4 mins ago',
    isCurrentSession: false,
    isTrusted: true,
  },
  {
    id: 'ses-003',
    userId: 'usr-hr-01',
    userName: 'Hitha, Kusuma',
    userEmail: '[EMAIL_ADDRESS]',
    role: 'hr',
    device: 'Desktop',
    browser: 'Edge 128 / Windows 11',
    os: 'Windows 11',
    ipAddress: '106.51.24.89',
    location: 'Bengaluru, Karnataka',
    loginTime: '2026-09-25T08:45:00Z',
    lastActive: '1 min ago',
    isCurrentSession: false,
    isTrusted: true,
  },
  {
    id: 'ses-004',
    userId: 'usr-pto-01',
    userName: 'Prof. Chandrasekhar',
    userEmail: 'placement@rvce.edu.in',
    role: 'pto',
    device: 'Desktop',
    browser: 'Chrome 128 / Windows 10',
    os: 'Windows 10',
    ipAddress: '117.218.44.10',
    location: 'Bengaluru, Karnataka (RVCE Campus)',
    loginTime: '2026-09-25T09:10:00Z',
    lastActive: '12 mins ago',
    isCurrentSession: false,
    isTrusted: true,
  },
  {
    id: 'ses-005',
    userId: 'usr-stu-01',
    userName: 'Bharath Royal',
    userEmail: 'bharath@gmail.com',
    role: 'student',
    device: 'Mobile',
    browser: 'Mobile Safari / iOS 18',
    os: 'iOS',
    ipAddress: '49.207.210.45',
    location: 'Mysuru, Karnataka',
    loginTime: '2026-09-25T09:25:00Z',
    lastActive: '15 mins ago',
    isCurrentSession: false,
    isTrusted: true,
  },
];

export const LOGIN_HISTORY_EVENTS: SecurityLoginEvent[] = [
  { id: 'log-01', email: '[EMAIL_ADDRESS]', status: 'Success', ipAddress: '115.112.82.14', browser: 'Chrome 128', device: 'Laptop', location: 'Bengaluru, Karnataka', timestamp: '2026-09-25T08:00:00Z' },
  { id: 'log-02', email: 'guest.unknown@rvce.in', status: 'Blocked', ipAddress: '45.143.201.88', browser: 'Python Requests', device: 'Unknown', location: 'Foreign Proxy', timestamp: '2026-09-25T05:30:00Z', failureReason: 'Too many failed password attempts. IP quarantined.' },
  { id: 'log-03', email: 'placement@rvce.edu.in', status: 'Success', ipAddress: '117.218.44.10', browser: 'Chrome 128', device: 'Desktop', location: 'Bengaluru, Karnataka', timestamp: '2026-09-25T09:10:00Z' },
  { id: 'log-04', email: 'bharath@gmail.com', status: 'Success', ipAddress: '49.207.210.45', browser: 'Mobile Safari', device: 'Mobile', location: 'Mysuru, Karnataka', timestamp: '2026-09-25T09:25:00Z' },
  { id: 'log-05', email: 'divya.hr@globalquest.in', status: 'Password Reset', ipAddress: '106.51.24.95', browser: 'Edge 128', device: 'Laptop', location: 'Bengaluru, Karnataka', timestamp: '2026-09-24T18:40:00Z' },
];

// ==========================================
// 6. SYSTEM BACKUPS & RESTORE POINTS
// ==========================================
export const SYSTEM_BACKUPS: SystemBackupRecord[] = [
  {
    id: 'bcp-2026-09-24',
    name: 'GQT_Full_Platform_Daily_Backup_20260924_2300',
    backupType: 'Full Platform',
    createdAt: '2026-09-24T23:00:00Z',
    size: '124.6 GB',
    status: 'Verified',
    createdBy: 'Automated Nightly Snapshot Worker',
    checksum: 'sha256:8f4c2e1b9a7d6e5f3c2b1a0d9e8f7c6b5a4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f',
    includedModules: ['Database', 'Storage Metadata', 'Settings', 'Templates', 'Question Bank', 'Audit Logs'],
  },
  {
    id: 'bcp-2026-09-23',
    name: 'GQT_Full_Platform_Daily_Backup_20260923_2300',
    backupType: 'Full Platform',
    createdAt: '2026-09-23T23:00:00Z',
    size: '122.1 GB',
    status: 'Verified',
    createdBy: 'Automated Nightly Snapshot Worker',
    checksum: 'sha256:7e3b1d0a8f6c5e4d2b1a9c8f7e6d5b4a3c2e1f0a9b8d7c6e5f4a3b2c1d0e9f8a',
    includedModules: ['Database', 'Storage Metadata', 'Settings', 'Templates', 'Question Bank', 'Audit Logs'],
  },
  {
    id: 'bcp-qb-2026-09-20',
    name: 'GQT_Question_Bank_Checkpoint_20260920',
    backupType: 'Question Bank',
    createdAt: '2026-09-20T16:00:00Z',
    size: '4.8 GB',
    status: 'Verified',
    createdBy: 'G.R Narendra Reddy (Pre-Drive Checkpoint)',
    checksum: 'sha256:6d2a0c9e7f5b4d3a1c0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b',
    includedModules: ['Question Bank', 'Question Papers', 'Evaluation Rubrics'],
  },
  {
    id: 'bcp-settings-2026-09-18',
    name: 'GQT_Settings_and_Templates_Export_20260918',
    backupType: 'Settings & Templates',
    createdAt: '2026-09-18T12:00:00Z',
    size: '850 MB',
    status: 'Verified',
    createdBy: 'Super Admin',
    checksum: 'sha256:5c1f9b8d6e4a3c2f0b9e8d7c6b5a4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c',
    includedModules: ['Branding Settings', 'Role Permissions', 'Portal Visibility', 'WhatsApp Templates', 'Email Templates'],
  },
];

// ==========================================
// 7. API KEYS & INTEGRATIONS
// ==========================================
export const INTEGRATIONS_LIST: IntegrationConfig[] = [
  {
    id: 'int-supabase',
    serviceKey: 'supabase',
    name: 'Supabase Enterprise Postgres & Realtime',
    description: 'PostgreSQL database, Row-Level Security, authentication, and WebSocket realtime replication.',
    status: 'Connected',
    apiUrl: 'https://xyzcompany.supabase.co',
    apiKeyMasked: 'sbp_live_••••••••••••••••••••••••••••942a',
    lastTested: '2 mins ago',
  },
  {
    id: 'int-whatsapp',
    serviceKey: 'whatsapp',
    name: 'Meta WhatsApp Cloud Business API',
    description: 'Official Meta Cloud API gateway for automated templated notifications and college drive group management.',
    status: 'Connected',
    apiUrl: 'https://graph.facebook.com/v20.0',
    apiKeyMasked: 'EAAG••••••••••••••••••••••••••••412k',
    senderId: '+91 80 4123 4567 (Verified GQT Green Badge)',
    webhookUrl: 'https://gqt-csr.globalquesttechnologies.com/api/webhooks/whatsapp',
    lastTested: '10 mins ago',
  },
  {
    id: 'int-smtp',
    serviceKey: 'smtp',
    name: 'Corporate SMTP Dispatch Engine',
    description: 'High-reputation transactional and broadcast HTML email engine for offer letters and circulars.',
    status: 'Connected',
    apiUrl: 'smtp.sendgrid.net:587 (TLS)',
    apiKeyMasked: 'SG.live_••••••••••••••••••••••••••••781c',
    senderId: 'noreply@globalquesttechnologies.com',
    lastTested: '15 mins ago',
  },
  {
    id: 'int-razorpay',
    serviceKey: 'razorpay',
    name: 'Razorpay Payment Gateway (Future Upgrades)',
    description: 'Payment gateway integration for voluntary specialized certification upgrades.',
    status: 'Configured',
    apiUrl: 'https://api.razorpay.com/v1',
    apiKeyMasked: 'rzp_live_••••••••••••••••••••••••••••109b',
    lastTested: '3 days ago',
  },
  {
    id: 'int-google',
    serviceKey: 'google_oauth',
    name: 'Google Workspace Single Sign-On (OAuth 2.0)',
    description: 'Institutional domain authentication for university placement officers and faculty.',
    status: 'Connected',
    apiUrl: 'https://accounts.google.com',
    apiKeyMasked: 'client_id: 8421098••••.apps.googleusercontent.com',
    lastTested: '1 day ago',
  },
  {
    id: 'int-microsoft',
    serviceKey: 'microsoft_oauth',
    name: 'Microsoft Entra ID (Azure AD)',
    description: 'Corporate executive Single Sign-On for Director and Founder access.',
    status: 'Connected',
    apiUrl: 'https://login.microsoftonline.com/common',
    apiKeyMasked: 'tenant_id: 4821a098••••••••••••••••',
    lastTested: '1 day ago',
  },
  {
    id: 'int-zoom',
    serviceKey: 'zoom',
    name: 'Zoom & Google Meet Auto-Provisioning',
    description: 'Auto-generates secure virtual interview rooms for remote candidate technical rounds.',
    status: 'Connected',
    apiUrl: 'https://api.zoom.us/v2',
    apiKeyMasked: 'z_token: eyJhbGciOiJIUzI1Ni••••••••••••',
    lastTested: '4 hours ago',
  },
];

// ==========================================
// 8. SYSTEM HEALTH & ERROR LOGS
// ==========================================
export const SYSTEM_HEALTH_METRICS: SystemHealthMetric[] = [
  { service: 'Supabase Postgres Database', status: 'Healthy', latencyMs: 14, uptimePct: 99.98, lastChecked: 'Just now', details: 'Connection pool 18/60 active • 0 lock contention' },
  { service: 'Realtime WebSockets (State Channel)', status: 'Healthy', latencyMs: 22, uptimePct: 99.95, lastChecked: 'Just now', details: '12 cluster nodes synchronized • 0 dropped packets' },
  { service: 'Edge Middleware & URL Router', status: 'Healthy', latencyMs: 8, uptimePct: 100.0, lastChecked: 'Just now', details: 'Cloudflare / Next.js edge proxy operational' },
  { service: 'Meta WhatsApp Cloud API Gateway', status: 'Healthy', latencyMs: 145, uptimePct: 99.8, lastChecked: '1 min ago', details: 'Queue depth: 0 • Deliverability: 98.4%' },
  { service: 'Corporate SMTP Mail Relay', status: 'Healthy', latencyMs: 110, uptimePct: 99.9, lastChecked: '1 min ago', details: 'Queue depth: 0 • TLS 1.3 enforced' },
  { service: 'Storage Object Store (S3 Compatible)', status: 'Healthy', latencyMs: 38, uptimePct: 99.99, lastChecked: 'Just now', details: '8 private/public buckets reachable' },
];

export const ADMIN_ERROR_LOGS: AdminErrorLog[] = [
  {
    id: 'err-001',
    timestamp: '2026-09-25T03:15:20Z',
    level: 'Warning',
    source: 'WhatsApp Webhook',
    message: 'Meta Cloud API callback delayed for +91 98450 77123 (Network timeout retry succeeded).',
    status: 'Resolved',
    resolvedBy: 'Auto-Retry Worker',
    resolvedAt: '2026-09-25T03:15:25Z',
  },
  {
    id: 'err-002',
    timestamp: '2026-09-24T21:40:12Z',
    level: 'Critical',
    source: 'Realtime WebSocket',
    message: 'Temporary client reconnection burst during shift from Exam Slot 1 to Slot 2 (recovered in 3.2s).',
    status: 'Resolved',
    resolvedBy: 'Load Balancer Cluster',
    resolvedAt: '2026-09-24T21:40:16Z',
  },
  {
    id: 'err-003',
    timestamp: '2026-09-24T14:10:00Z',
    level: 'Error',
    source: 'Next.js Server',
    message: 'Candidate USN duplicate registration attempt blocked cleanly by database unique constraint.',
    status: 'Resolved',
    resolvedBy: 'System Constraint',
    resolvedAt: '2026-09-24T14:10:01Z',
  },
];
