import { OfferLetter, OfferTemplate, BatchRecord, JoiningConfirmationRecord, AdmissionVerificationRecord } from "@/types";

export const INITIAL_OFFER_LETTERS: OfferLetter[] = [
  {
    id: "off-001",
    offerNumber: "GQT/OFFER/2026/001",
    studentId: "stu-001",
    studentName: "Aditya V. Kashyap",
    studentEmail: "aditya.kashyap@rvce.edu.in",
    studentPhone: "+91 98450 11992",
    collegeName: "R.V. College of Engineering (RVCE)",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    roleTitle: "Associate Software Engineer - Java & Agentic AI",
    course: "Java Full Stack + Agentic AI",
    branch: "Computer Science and Engineering",
    batch: "2026 Batch Alpha",
    ctc: "₹ 6.50 LPA",
    stipendDuringInternship: "₹ 18,000 / month",
    location: "Bengaluru, Karnataka",
    reportingTime: "09:00 AM",
    trainingCenter: "GQT Advanced Learning Center, Whitefield, Bengaluru",
    trainingMode: "Hybrid",
    trainingType: "CSR Sponsored",
    courseFee: "₹ 75,000 (100% CSR Subsidized)",
    csrSponsorship: "Global Quest Technologies CSR Foundation",
    bond: "None (Zero Bond Policy)",
    hrExecutive: "Priya Nair",
    joiningDate: "2026-07-01",
    offerIssuedDate: "2026-09-24",
    validUntil: "2026-10-15",
    status: "Accepted",
    qrVerificationCode: "GQT-VERIFY-2026-STU-001-RVCE-9845",
    digitalSignatureUrl: "/images/signatures/director-signature.png",
    authorizedSignatory: "G.R. Narendra Reddy",
    authorizedDesignation: "Director - Talent Enablement & CSR",
    companySealUrl: "/images/signatures/gqt-seal.png",
    watermarkEnabled: true,
    remarks: "Eligible for fast-track performance bonus after 6 months.",
    pdfUrl: "/documents/offers/GQT_OFFER_2026_001_Aditya_Kashyap.pdf",
    deliveryChannel: "Both",
    openedAt: "2026-09-24T14:30:00Z",
    downloadedAt: "2026-09-24T14:35:00Z",
    downloadsCount: 3,
    acceptedAt: "2026-09-24T15:20:00Z",
    acceptedIp: "106.51.240.18",
    acceptedBrowser: "Chrome 128.0.0 / macOS",
    acceptedDevice: "MacBook Pro",
  },
  {
    id: "off-002",
    offerNumber: "GQT/OFFER/2026/002",
    studentId: "stu-002",
    studentName: "Sneha Ramachandra Rao",
    studentEmail: "sneha.rao@bmsce.ac.in",
    studentPhone: "+91 98451 22334",
    collegeName: "B.M.S. College of Engineering (BMSCE)",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    roleTitle: "Junior AI Engineer - Python Full Stack",
    course: "Python Full Stack + AI/ML",
    branch: "Information Science and Engineering",
    batch: "2026 Batch Alpha",
    ctc: "₹ 6.50 LPA",
    stipendDuringInternship: "₹ 18,000 / month",
    location: "Bengaluru, Karnataka",
    reportingTime: "09:00 AM",
    trainingCenter: "GQT Advanced Learning Center, Whitefield, Bengaluru",
    trainingMode: "Hybrid",
    trainingType: "CSR Sponsored",
    courseFee: "₹ 75,000 (100% CSR Subsidized)",
    csrSponsorship: "Global Quest Technologies CSR Foundation",
    bond: "None (Zero Bond Policy)",
    hrExecutive: "Arun Menon",
    joiningDate: "2026-07-01",
    offerIssuedDate: "2026-09-24",
    validUntil: "2026-10-15",
    status: "Sent",
    qrVerificationCode: "GQT-VERIFY-2026-STU-002-BMS-4412",
    digitalSignatureUrl: "/images/signatures/director-signature.png",
    authorizedSignatory: "G.R. Narendra Reddy",
    authorizedDesignation: "Director - Talent Enablement & CSR",
    companySealUrl: "/images/signatures/gqt-seal.png",
    watermarkEnabled: true,
    remarks: "Top rank candidate from BMSCE in AI track.",
    pdfUrl: "/documents/offers/GQT_OFFER_2026_002_Sneha_Rao.pdf",
    deliveryChannel: "Both",
    openedAt: "2026-09-24T18:10:00Z",
    downloadedAt: "2026-09-24T18:15:00Z",
    downloadsCount: 1,
  },
  {
    id: "off-003",
    offerNumber: "GQT/OFFER/2026/003",
    studentId: "stu-003",
    studentName: "Karthik Srinivas",
    studentEmail: "karthik.s@msrit.edu",
    studentPhone: "+91 98452 33445",
    collegeName: "Ramaiah Institute of Technology (MSRIT)",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    roleTitle: "Full Stack Web Developer - MERN & Cloud",
    course: "MERN Stack + Cloud",
    branch: "Computer Science & Engineering",
    batch: "2026 Batch Alpha",
    ctc: "₹ 5.50 LPA",
    stipendDuringInternship: "₹ 15,000 / month",
    location: "Bengaluru, Karnataka",
    reportingTime: "09:30 AM",
    trainingCenter: "GQT Advanced Learning Center, Whitefield, Bengaluru",
    trainingMode: "Offline Campus",
    trainingType: "CSR Sponsored",
    courseFee: "₹ 70,000 (100% CSR Subsidized)",
    csrSponsorship: "Global Quest Technologies CSR Foundation",
    bond: "None (Zero Bond Policy)",
    hrExecutive: "Divya H",
    joiningDate: "2026-07-01",
    offerIssuedDate: "2026-09-24",
    validUntil: "2026-10-15",
    status: "Generated",
    qrVerificationCode: "GQT-VERIFY-2026-STU-003-MSR-3319",
    digitalSignatureUrl: "/images/signatures/director-signature.png",
    authorizedSignatory: "G.R. Narendra Reddy",
    authorizedDesignation: "Director - Talent Enablement & CSR",
    companySealUrl: "/images/signatures/gqt-seal.png",
    watermarkEnabled: true,
    remarks: "Pending HR send dispatch.",
    pdfUrl: "/documents/offers/GQT_OFFER_2026_003_Karthik_Srinivas.pdf",
    deliveryChannel: "Student Portal",
    downloadsCount: 0,
  },
  {
    id: "off-004",
    offerNumber: "GQT/OFFER/2026/004",
    studentId: "stu-007",
    studentName: "Meghana Deshmukh",
    studentEmail: "meghana.d@pes.edu",
    studentPhone: "+91 98456 77889",
    collegeName: "PES University, Bengaluru",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    roleTitle: "Associate Software Engineer - Java & Cloud",
    course: "Java Full Stack + Agentic AI",
    branch: "Computer Science & Engineering",
    batch: "2026 Batch Alpha",
    ctc: "₹ 6.50 LPA",
    stipendDuringInternship: "₹ 18,000 / month",
    location: "Bengaluru, Karnataka",
    reportingTime: "09:00 AM",
    trainingCenter: "GQT Advanced Learning Center, Bengaluru",
    trainingMode: "Hybrid",
    trainingType: "CSR Sponsored",
    courseFee: "₹ 75,000 (100% CSR Subsidized)",
    csrSponsorship: "Global Quest Technologies CSR Foundation",
    bond: "None",
    hrExecutive: "Priya Nair",
    joiningDate: "2026-07-01",
    offerIssuedDate: "2026-09-20",
    validUntil: "2026-10-05",
    status: "Draft",
    qrVerificationCode: "GQT-VERIFY-2026-STU-007-PES-7712",
    digitalSignatureUrl: "/images/signatures/director-signature.png",
    watermarkEnabled: true,
    remarks: "Awaiting final Dean approval signature.",
  },
  {
    id: "off-005",
    offerNumber: "GQT/OFFER/2026/005",
    studentId: "stu-008",
    studentName: "Varun K. Shetty",
    studentEmail: "varun.shetty@sitm.ac.in",
    studentPhone: "+91 98457 88990",
    collegeName: "Sahyadri College of Engineering, Mangaluru",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    roleTitle: "Junior Data Analyst - Python & SQL",
    course: "Data Analytics & Engineering",
    branch: "Information Science & Engineering",
    batch: "2026 Batch Beta",
    ctc: "₹ 5.00 LPA",
    stipendDuringInternship: "₹ 14,000 / month",
    location: "Bengaluru, Karnataka",
    reportingTime: "10:00 AM",
    trainingCenter: "GQT Advanced Learning Center, Bengaluru",
    trainingMode: "Virtual Live",
    trainingType: "CSR Sponsored",
    courseFee: "₹ 65,000 (100% CSR Subsidized)",
    csrSponsorship: "Global Quest Technologies CSR Foundation",
    bond: "None",
    hrExecutive: "Divya H",
    joiningDate: "2026-08-01",
    offerIssuedDate: "2026-09-15",
    validUntil: "2026-09-22",
    status: "Expired",
    qrVerificationCode: "GQT-VERIFY-2026-STU-008-SAH-8821",
    digitalSignatureUrl: "/images/signatures/director-signature.png",
    watermarkEnabled: true,
    remarks: "Candidate did not respond within validity window.",
    deliveryChannel: "Both",
  },
  {
    id: "off-006",
    offerNumber: "GQT/OFFER/2026/006",
    studentId: "stu-009",
    studentName: "Praveen Kumar",
    studentEmail: "praveen.k@sjce.ac.in",
    studentPhone: "+91 98458 99001",
    collegeName: "JSS Science & Technology University (SJCE), Mysuru",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    roleTitle: "QA Automation Engineer",
    course: "Software Testing & Automation",
    branch: "Electronics & Communication Engineering",
    batch: "2026 Batch Beta",
    ctc: "₹ 4.80 LPA",
    stipendDuringInternship: "₹ 14,000 / month",
    location: "Mysuru, Karnataka",
    reportingTime: "09:30 AM",
    trainingCenter: "GQT Hubballi-Mysuru Skill Hub",
    trainingMode: "Offline Campus",
    trainingType: "CSR Sponsored",
    courseFee: "₹ 60,000 (100% CSR Subsidized)",
    csrSponsorship: "Global Quest Technologies CSR Foundation",
    bond: "None",
    hrExecutive: "Arun Menon",
    joiningDate: "2026-08-01",
    offerIssuedDate: "2026-09-18",
    validUntil: "2026-10-02",
    status: "Rejected",
    qrVerificationCode: "GQT-VERIFY-2026-STU-009-JSS-9912",
    digitalSignatureUrl: "/images/signatures/director-signature.png",
    watermarkEnabled: true,
    rejectionReason: "Higher Studies",
    rejectionRemarks: "Admitted into MS program at RWTH Aachen Germany.",
    rejectedAt: "2026-09-21T11:00:00Z",
    deliveryChannel: "Both",
  },
];

export const INITIAL_OFFER_TEMPLATES: OfferTemplate[] = [
  {
    id: "tmpl-java",
    title: "Java Full Stack + Agentic AI Enterprise Offer",
    courseTrack: "Java Full Stack + Agentic AI",
    description: "Flagship GQT CSR employment letter with cloud development, AI orchestration, and stipend terms.",
    version: 3,
    isActive: true,
    placeholders: [
      "{{student_name}}",
      "{{student_id}}",
      "{{usn}}",
      "{{college}}",
      "{{course}}",
      "{{branch}}",
      "{{joining_date}}",
      "{{reporting_time}}",
      "{{location}}",
      "{{batch}}",
      "{{offer_number}}",
      "{{ctc}}",
      "{{stipend}}",
      "{{academic_year}}",
    ],
    lastModifiedBy: "G.R. Narendra Reddy (Super Admin)",
    updatedAt: "2026-09-22T10:00:00Z",
    content: `# LETTER OF INTENT (LOI) & CONDITIONAL OFFER OF ADMISSION

**Ref No:** {{offer_number}}  
**Date:** {{offer_issued_date}}  

Dear **{{student_name}}** (USN: {{usn}}),  
**College:** {{college}}  
**Branch:** {{branch}}  

On behalf of **Global Quest Technologies Pvt. Ltd.** and the **GQT CSR Foundation**, we are pleased to offer you conditional selection for the position of **{{role_title}}** under the **{{academic_year}} CSR Flagship Enablement Drive**.

### 1. Position & Course Track
- **Assigned Track:** {{course}}
- **Training Cohort:** {{batch}}
- **Reporting Date:** {{joining_date}} at {{reporting_time}}
- **Training Center:** {{location}}

### 2. Remuneration & Corporate Sponsorship
- **Full-Time Compensation (CTC):** {{ctc}}
- **Internship Stipend:** {{stipend}}
- **Tuition Sponsorship:** 100% CSR Subsidized by Global Quest Technologies
- **Bond Clause:** No financial or service bond required.

### 3. Acceptance & Verification
Please review and digitally accept this offer via your GQT Student Portal on or before **{{valid_until}}**, failing which this offer shall expire automatically.

Warm regards,  
**Director of Talent Enablement & CSR**  
Global Quest Technologies Pvt. Ltd.`,
  },
  {
    id: "tmpl-python",
    title: "Python Full Stack + AI/ML Offer Template",
    courseTrack: "Python Full Stack + AI/ML",
    description: "Template for data science, machine learning, and Python enterprise full stack hiring.",
    version: 2,
    isActive: true,
    placeholders: [
      "{{student_name}}",
      "{{student_id}}",
      "{{college}}",
      "{{course}}",
      "{{joining_date}}",
      "{{batch}}",
      "{{offer_number}}",
      "{{ctc}}",
    ],
    lastModifiedBy: "Priya Nair (HR Lead)",
    updatedAt: "2026-09-20T14:30:00Z",
    content: `# LETTER OF INTENT — PYTHON & ARTIFICIAL INTELLIGENCE TRACK

**Offer Number:** {{offer_number}}  
Congratulations {{student_name}}! Following your outstanding assessment performance at {{college}}, Global Quest Technologies offers you the role of Junior AI Engineer.`,
  },
  {
    id: "tmpl-testing",
    title: "Software Testing & QA Automation Template",
    courseTrack: "Software Testing & Automation",
    description: "Template tailored for quality assurance, Selenium automation, and CI/CD pipelines.",
    version: 1,
    isActive: true,
    placeholders: [
      "{{student_name}}",
      "{{college}}",
      "{{course}}",
      "{{joining_date}}",
      "{{batch}}",
      "{{offer_number}}",
    ],
    lastModifiedBy: "Arun Menon",
    updatedAt: "2026-09-18T16:00:00Z",
    content: `# CONDITIONAL OFFER LETTER — QUALITY ENGINEERING & AUTOMATION

**Ref:** {{offer_number}}  
Dear {{student_name}}, Global Quest Technologies extends this conditional offer for QA Automation Engineering.`,
  },
  {
    id: "tmpl-mern",
    title: "MERN Stack + Cloud Architecture Template",
    courseTrack: "MERN Stack + Cloud",
    description: "Full stack JavaScript, React, Node.js, and cloud native microservices template.",
    version: 1,
    isActive: true,
    placeholders: [
      "{{student_name}}",
      "{{college}}",
      "{{course}}",
      "{{batch}}",
      "{{offer_number}}",
    ],
    lastModifiedBy: "Divya H",
    updatedAt: "2026-09-19T11:00:00Z",
    content: `# LETTER OF INTENT — MERN FULL STACK ENGINEERING`,
  },
];

export const INITIAL_BATCHES: BatchRecord[] = [
  {
    id: "bat-001",
    batchCode: "GQT-2026-JFS-ALPHA",
    name: "2026 Batch Alpha — Java Cloud & AI",
    course: "Java Full Stack + Agentic AI",
    trainer: "Dr. Shankar Prasad & Lead Cloud SRE",
    startDate: "2026-07-01",
    endDate: "2026-12-31",
    capacity: 60,
    enrolledCount: 42,
    mode: "Hybrid",
    location: "GQT Advanced Learning Center, Whitefield, Bengaluru",
    status: "Active",
    studentIds: ["stu-001"],
  },
  {
    id: "bat-002",
    batchCode: "GQT-2026-PY-ALPHA",
    name: "2026 Batch Alpha — Python & AI/ML",
    course: "Python Full Stack + AI/ML",
    trainer: "Arun Menon & Senior Data Scientist",
    startDate: "2026-07-01",
    endDate: "2026-12-31",
    capacity: 50,
    enrolledCount: 38,
    mode: "Hybrid",
    location: "GQT Advanced Learning Center, Whitefield, Bengaluru",
    status: "Active",
    studentIds: ["stu-002"],
  },
  {
    id: "bat-003",
    batchCode: "GQT-2026-MERN-ALPHA",
    name: "2026 Batch Alpha — MERN Cloud",
    course: "MERN Stack + Cloud",
    trainer: "Divya H & Full Stack Architect",
    startDate: "2026-07-01",
    endDate: "2026-12-31",
    capacity: 45,
    enrolledCount: 45,
    mode: "Offline Campus",
    location: "GQT Bengaluru Center",
    status: "Full",
    studentIds: ["stu-003"],
  },
  {
    id: "bat-004",
    batchCode: "GQT-2026-MYS-BETA",
    name: "2026 Batch Beta — Regional Mysuru Cohort",
    course: "Java Full Stack + Agentic AI",
    trainer: "Priya Nair & Lead Tech Trainer",
    startDate: "2026-08-01",
    endDate: "2027-01-31",
    capacity: 60,
    enrolledCount: 18,
    mode: "Offline Campus",
    location: "GQT Mysuru Regional Center, Hebbal Industrial Area, Mysuru",
    status: "Upcoming",
    studentIds: [],
  },
];

export const INITIAL_JOINING_CONFIRMATIONS: JoiningConfirmationRecord[] = [
  {
    id: "jc-001",
    studentId: "stu-001",
    studentName: "Aditya V. Kashyap",
    usn: "1RV22CS014",
    collegeName: "R.V. College of Engineering (RVCE)",
    offerNumber: "GQT/OFFER/2026/001",
    batchCode: "GQT-2026-JFS-ALPHA",
    reportingDate: "2026-07-01",
    reportingTime: "09:00 AM",
    mode: "Hybrid",
    location: "GQT Advanced Learning Center, Whitefield, Bengaluru",
    emergencyContact: {
      name: "Vijay Kashyap (Father)",
      relationship: "Parent",
      phone: "+91 98450 99887",
    },
    confirmedAt: "2026-09-24T16:00:00Z",
    acknowledgedTerms: true,
    status: "Confirmed",
  },
];

export const INITIAL_ADMISSION_VERIFICATIONS: AdmissionVerificationRecord[] = [
  {
    id: "av-001",
    studentId: "stu-001",
    studentName: "Aditya V. Kashyap",
    usn: "1RV22CS014",
    collegeName: "R.V. College of Engineering (RVCE)",
    offerNumber: "GQT/OFFER/2026/001",
    overallStatus: "Approved",
    assignedBatch: "GQT-2026-JFS-ALPHA",
    joinedAt: "2026-09-24T16:15:00Z",
    admissionRemarks: "All VTU marks cards, Aadhaar, and College Bonafide authenticated.",
    documents: [
      { type: "Resume", url: "/documents/resumes/Resume_Aditya_RVCE.pdf", status: "Approved", verifiedAt: "2026-09-24T16:05:00Z", verifiedBy: "Admission Officer - Ravi" },
      { type: "Photo", url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200", status: "Approved", verifiedAt: "2026-09-24T16:05:00Z", verifiedBy: "Admission Officer - Ravi" },
      { type: "College ID", url: "/documents/ids/RVCE_ID_Aditya.pdf", status: "Approved", verifiedAt: "2026-09-24T16:06:00Z", verifiedBy: "Admission Officer - Ravi" },
      { type: "Aadhaar", url: "/documents/kyc/Aadhaar_Aditya.pdf", status: "Approved", verifiedAt: "2026-09-24T16:07:00Z", verifiedBy: "Admission Officer - Ravi" },
      { type: "Marks Cards", url: "/documents/academic/VTU_Sem1_7_Aditya.pdf", status: "Approved", verifiedAt: "2026-09-24T16:08:00Z", verifiedBy: "Admission Officer - Ravi" },
      { type: "Bonafide Certificate", url: "/documents/bonafide/RVCE_Bonafide_Aditya.pdf", status: "Approved", verifiedAt: "2026-09-24T16:09:00Z", verifiedBy: "Admission Officer - Ravi" },
    ],
  },
  {
    id: "av-002",
    studentId: "stu-002",
    studentName: "Sneha Ramachandra Rao",
    usn: "1BM22IS089",
    collegeName: "B.M.S. College of Engineering (BMSCE)",
    offerNumber: "GQT/OFFER/2026/002",
    overallStatus: "Pending Review",
    assignedBatch: "GQT-2026-PY-ALPHA",
    documents: [
      { type: "Resume", url: "/documents/resumes/Resume_Sneha_BMSCE.pdf", status: "Approved", verifiedAt: "2026-09-24T17:00:00Z", verifiedBy: "Admission Officer - Ravi" },
      { type: "Photo", url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200", status: "Approved", verifiedAt: "2026-09-24T17:00:00Z", verifiedBy: "Admission Officer - Ravi" },
      { type: "College ID", url: "/documents/ids/BMSCE_ID_Sneha.pdf", status: "Pending" },
      { type: "Aadhaar", url: "/documents/kyc/Aadhaar_Sneha.pdf", status: "Approved", verifiedAt: "2026-09-24T17:02:00Z", verifiedBy: "Admission Officer - Ravi" },
      { type: "Marks Cards", url: "/documents/academic/BMSCE_Sem1_7_Sneha.pdf", status: "Pending" },
      { type: "Bonafide Certificate", url: "/documents/bonafide/BMSCE_Bonafide_Sneha.pdf", status: "Pending" },
    ],
  },
];
