import {
  DistrictStatistics,
  CollegePerformanceStats,
  HRPerformanceStats,
  PipelineFunnelStage,
  CourseAnalyticsData,
  BranchAnalyticsData,
  TrainingBatchMetric,
  ExecutiveSavedReport,
  ManagementAuditEntry,
  ManagementActivityFeedItem,
  ExecutiveInsightsItem,
} from '@/types';

// =========================================================================
// 1. ALL 31 KARNATAKA DISTRICTS WITH COMPREHENSIVE CSR TELEMETRY
// =========================================================================
export const KARNATAKA_DISTRICTS: DistrictStatistics[] = [
  {
    id: 'dist-blr-u',
    district: 'Bengaluru Urban',
    zone: 'Bengaluru Metro',
    collegesCount: 38,
    drivesCount: 16,
    studentsRegistered: 4850,
    studentsExamAppeared: 4420,
    studentsQualified: 3120,
    studentsSelected: 1140,
    offersAccepted: 1045,
    joiningConfirmed: 920,
    selectionRate: 25.8,
    offerAcceptanceRate: 91.7,
    activeHRExecutives: 6,
    topColleges: ['R.V. College of Engineering', 'B.M.S. College of Engineering', 'Ramaiah Institute of Technology', 'PES University'],
    growthYoY: 18.5,
    monthlyTrends: [
      { month: 'Jun', registered: 420, selected: 95 },
      { month: 'Jul', registered: 890, selected: 210 },
      { month: 'Aug', registered: 1540, selected: 380 },
      { month: 'Sep', registered: 2000, selected: 455 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 1850 },
      { branch: 'ISE', count: 980 },
      { branch: 'ECE', count: 920 },
      { branch: 'AIML', count: 650 },
      { branch: 'Others', count: 450 },
    ],
  },
  {
    id: 'dist-blr-r',
    district: 'Bengaluru Rural',
    zone: 'Bengaluru Metro',
    collegesCount: 9,
    drivesCount: 4,
    studentsRegistered: 860,
    studentsExamAppeared: 780,
    studentsQualified: 490,
    studentsSelected: 175,
    offersAccepted: 158,
    joiningConfirmed: 138,
    selectionRate: 22.4,
    offerAcceptanceRate: 90.3,
    activeHRExecutives: 2,
    topColleges: ['Gitamex Institute of Tech', 'Devanahalli College of Engg', 'Nagarjuna College of Engineering'],
    growthYoY: 14.2,
    monthlyTrends: [
      { month: 'Jun', registered: 80, selected: 15 },
      { month: 'Jul', registered: 190, selected: 38 },
      { month: 'Aug', registered: 270, selected: 52 },
      { month: 'Sep', registered: 320, selected: 70 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 340 },
      { branch: 'ECE', count: 210 },
      { branch: 'Mechanical', count: 160 },
      { branch: 'Civil', count: 150 },
    ],
  },
  {
    id: 'dist-mys',
    district: 'Mysuru',
    zone: 'South',
    collegesCount: 14,
    drivesCount: 7,
    studentsRegistered: 1940,
    studentsExamAppeared: 1780,
    studentsQualified: 1180,
    studentsSelected: 440,
    offersAccepted: 405,
    joiningConfirmed: 350,
    selectionRate: 24.7,
    offerAcceptanceRate: 92.0,
    activeHRExecutives: 3,
    topColleges: ['The National Institute of Engineering (NIE)', 'Sri Jayachamarajendra College of Engineering (SJCE)', 'GSSS Institute'],
    growthYoY: 16.8,
    monthlyTrends: [
      { month: 'Jun', registered: 180, selected: 40 },
      { month: 'Jul', registered: 410, selected: 92 },
      { month: 'Aug', registered: 620, selected: 148 },
      { month: 'Sep', registered: 730, selected: 160 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 720 },
      { branch: 'ISE', count: 410 },
      { branch: 'ECE', count: 390 },
      { branch: 'EEE', count: 220 },
      { branch: 'Civil', count: 200 },
    ],
  },
  {
    id: 'dist-bgm',
    district: 'Belagavi',
    zone: 'North',
    collegesCount: 16,
    drivesCount: 6,
    studentsRegistered: 1650,
    studentsExamAppeared: 1490,
    studentsQualified: 940,
    studentsSelected: 320,
    offersAccepted: 298,
    joiningConfirmed: 260,
    selectionRate: 21.5,
    offerAcceptanceRate: 93.1,
    activeHRExecutives: 2,
    topColleges: ['KLS Gogte Institute of Technology', 'KLE Technological University Campus', 'Maratha Mandal Engineering'],
    growthYoY: 22.4,
    monthlyTrends: [
      { month: 'Jun', registered: 140, selected: 28 },
      { month: 'Jul', registered: 310, selected: 64 },
      { month: 'Aug', registered: 540, selected: 108 },
      { month: 'Sep', registered: 660, selected: 120 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 620 },
      { branch: 'Mechanical', count: 380 },
      { branch: 'ECE', count: 340 },
      { branch: 'Civil', count: 310 },
    ],
  },
  {
    id: 'dist-dk',
    district: 'Dakshina Kannada',
    zone: 'Coastal',
    collegesCount: 15,
    drivesCount: 6,
    studentsRegistered: 1520,
    studentsExamAppeared: 1410,
    studentsQualified: 990,
    studentsSelected: 385,
    offersAccepted: 355,
    joiningConfirmed: 312,
    selectionRate: 27.3,
    offerAcceptanceRate: 92.2,
    activeHRExecutives: 2,
    topColleges: ['Canara Engineering College', 'St. Joseph Engineering College', 'Sahyadri College of Engg', 'Yenepoya'],
    growthYoY: 24.1,
    monthlyTrends: [
      { month: 'Jun', registered: 150, selected: 36 },
      { month: 'Jul', registered: 320, selected: 82 },
      { month: 'Aug', registered: 490, selected: 125 },
      { month: 'Sep', registered: 560, selected: 142 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 610 },
      { branch: 'ISE', count: 310 },
      { branch: 'ECE', count: 320 },
      { branch: 'AIML', count: 280 },
    ],
  },
  {
    id: 'dist-dwd',
    district: 'Dharwad',
    zone: 'North',
    collegesCount: 11,
    drivesCount: 5,
    studentsRegistered: 1280,
    studentsExamAppeared: 1160,
    studentsQualified: 740,
    studentsSelected: 260,
    offersAccepted: 240,
    joiningConfirmed: 205,
    selectionRate: 22.4,
    offerAcceptanceRate: 92.3,
    activeHRExecutives: 2,
    topColleges: ['SDM College of Engineering & Technology', 'B.V. Bhoomaraddi (KLE Tech)', 'IIT Dharwad Regionals'],
    growthYoY: 19.5,
    monthlyTrends: [
      { month: 'Jun', registered: 110, selected: 22 },
      { month: 'Jul', registered: 260, selected: 52 },
      { month: 'Aug', registered: 410, selected: 86 },
      { month: 'Sep', registered: 500, selected: 100 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 480 },
      { branch: 'ECE', count: 290 },
      { branch: 'Mechanical', count: 280 },
      { branch: 'Civil', count: 230 },
    ],
  },
  {
    id: 'dist-klb',
    district: 'Kalaburagi',
    zone: 'North',
    collegesCount: 10,
    drivesCount: 4,
    studentsRegistered: 1050,
    studentsExamAppeared: 940,
    studentsQualified: 520,
    studentsSelected: 165,
    offersAccepted: 152,
    joiningConfirmed: 130,
    selectionRate: 17.6,
    offerAcceptanceRate: 92.1,
    activeHRExecutives: 2,
    topColleges: ['PDA College of Engineering', 'Sharnbasva University', 'Appa Institute'],
    growthYoY: 31.0,
    monthlyTrends: [
      { month: 'Jun', registered: 90, selected: 14 },
      { month: 'Jul', registered: 210, selected: 32 },
      { month: 'Aug', registered: 350, selected: 55 },
      { month: 'Sep', registered: 400, selected: 64 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 390 },
      { branch: 'ECE', count: 240 },
      { branch: 'Civil', count: 220 },
      { branch: 'Mechanical', count: 200 },
    ],
  },
  {
    id: 'dist-smg',
    district: 'Shivamogga',
    zone: 'Central',
    collegesCount: 8,
    drivesCount: 4,
    studentsRegistered: 910,
    studentsExamAppeared: 820,
    studentsQualified: 510,
    studentsSelected: 160,
    offersAccepted: 148,
    joiningConfirmed: 125,
    selectionRate: 19.5,
    offerAcceptanceRate: 92.5,
    activeHRExecutives: 1,
    topColleges: ['JNNCE (Jawaharlal Nehru National College of Engg)', 'PES Institute of Tech Shivamogga'],
    growthYoY: 15.6,
    monthlyTrends: [
      { month: 'Jun', registered: 80, selected: 14 },
      { month: 'Jul', registered: 180, selected: 32 },
      { month: 'Aug', registered: 310, selected: 54 },
      { month: 'Sep', registered: 340, selected: 60 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 350 },
      { branch: 'ECE', count: 210 },
      { branch: 'Mechanical', count: 180 },
      { branch: 'Civil', count: 170 },
    ],
  },
  {
    id: 'dist-tmk',
    district: 'Tumakuru',
    zone: 'South',
    collegesCount: 9,
    drivesCount: 4,
    studentsRegistered: 980,
    studentsExamAppeared: 890,
    studentsQualified: 570,
    studentsSelected: 190,
    offersAccepted: 174,
    joiningConfirmed: 150,
    selectionRate: 21.3,
    offerAcceptanceRate: 91.6,
    activeHRExecutives: 1,
    topColleges: ['Siddaganga Institute of Technology (SIT)', 'Sri Siddhartha Institute of Technology'],
    growthYoY: 17.2,
    monthlyTrends: [
      { month: 'Jun', registered: 90, selected: 18 },
      { month: 'Jul', registered: 200, selected: 38 },
      { month: 'Aug', registered: 330, selected: 64 },
      { month: 'Sep', registered: 360, selected: 70 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 380 },
      { branch: 'ISE', count: 200 },
      { branch: 'ECE', count: 210 },
      { branch: 'Mechanical', count: 190 },
    ],
  },
  {
    id: 'dist-dvg',
    district: 'Davanagere',
    zone: 'Central',
    collegesCount: 7,
    drivesCount: 3,
    studentsRegistered: 790,
    studentsExamAppeared: 710,
    studentsQualified: 440,
    studentsSelected: 145,
    offersAccepted: 133,
    joiningConfirmed: 115,
    selectionRate: 20.4,
    offerAcceptanceRate: 91.7,
    activeHRExecutives: 1,
    topColleges: ['Bapuji Institute of Engineering and Technology (BIET)', 'UBDT College of Engineering'],
    growthYoY: 13.9,
    monthlyTrends: [
      { month: 'Jun', registered: 70, selected: 12 },
      { month: 'Jul', registered: 160, selected: 30 },
      { month: 'Aug', registered: 270, selected: 49 },
      { month: 'Sep', registered: 290, selected: 54 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 310 },
      { branch: 'ECE', count: 190 },
      { branch: 'Mechanical', count: 150 },
      { branch: 'Civil', count: 140 },
    ],
  },
  {
    id: 'dist-udp',
    district: 'Udupi',
    zone: 'Coastal',
    collegesCount: 8,
    drivesCount: 3,
    studentsRegistered: 840,
    studentsExamAppeared: 780,
    studentsQualified: 540,
    studentsSelected: 210,
    offersAccepted: 195,
    joiningConfirmed: 172,
    selectionRate: 26.9,
    offerAcceptanceRate: 92.9,
    activeHRExecutives: 1,
    topColleges: ['NMAM Institute of Technology (Nitte)', 'Shri Madhwa Vadiraja Institute of Tech'],
    growthYoY: 21.0,
    monthlyTrends: [
      { month: 'Jun', registered: 75, selected: 18 },
      { month: 'Jul', registered: 175, selected: 44 },
      { month: 'Aug', registered: 280, selected: 70 },
      { month: 'Sep', registered: 310, selected: 78 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 340 },
      { branch: 'ISE', count: 180 },
      { branch: 'ECE', count: 180 },
      { branch: 'AIML', count: 140 },
    ],
  },
  {
    id: 'dist-blr',
    district: 'Ballari',
    zone: 'North',
    collegesCount: 6,
    drivesCount: 3,
    studentsRegistered: 650,
    studentsExamAppeared: 580,
    studentsQualified: 330,
    studentsSelected: 98,
    offersAccepted: 90,
    joiningConfirmed: 76,
    selectionRate: 16.9,
    offerAcceptanceRate: 91.8,
    activeHRExecutives: 1,
    topColleges: ['Ballari Institute of Technology and Management (BITM)', 'Rao Bahadur Y. Mahabaleswarappa Engg'],
    growthYoY: 28.5,
    monthlyTrends: [
      { month: 'Jun', registered: 60, selected: 8 },
      { month: 'Jul', registered: 130, selected: 20 },
      { month: 'Aug', registered: 220, selected: 33 },
      { month: 'Sep', registered: 240, selected: 37 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 260 },
      { branch: 'ECE', count: 150 },
      { branch: 'Mechanical', count: 125 },
      { branch: 'Civil', count: 115 },
    ],
  },
  {
    id: 'dist-hsn',
    district: 'Hassan',
    zone: 'South',
    collegesCount: 6,
    drivesCount: 3,
    studentsRegistered: 620,
    studentsExamAppeared: 560,
    studentsQualified: 360,
    studentsSelected: 115,
    offersAccepted: 106,
    joiningConfirmed: 92,
    selectionRate: 20.5,
    offerAcceptanceRate: 92.2,
    activeHRExecutives: 1,
    topColleges: ['Malnad College of Engineering (MCE Hassan)', 'Government Engineering College Hassan'],
    growthYoY: 15.0,
    monthlyTrends: [
      { month: 'Jun', registered: 55, selected: 10 },
      { month: 'Jul', registered: 125, selected: 24 },
      { month: 'Aug', registered: 210, selected: 39 },
      { month: 'Sep', registered: 230, selected: 42 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 240 },
      { branch: 'ECE', count: 150 },
      { branch: 'Mechanical', count: 120 },
      { branch: 'Civil', count: 110 },
    ],
  },
  {
    id: 'dist-mnd',
    district: 'Mandya',
    zone: 'South',
    collegesCount: 5,
    drivesCount: 2,
    studentsRegistered: 510,
    studentsExamAppeared: 460,
    studentsQualified: 290,
    studentsSelected: 92,
    offersAccepted: 85,
    joiningConfirmed: 72,
    selectionRate: 20.0,
    offerAcceptanceRate: 92.4,
    activeHRExecutives: 1,
    topColleges: ['PES College of Engineering Mandya', 'Government Engineering College KR Pet'],
    growthYoY: 18.2,
    monthlyTrends: [
      { month: 'Jun', registered: 45, selected: 8 },
      { month: 'Jul', registered: 105, selected: 19 },
      { month: 'Aug', registered: 175, selected: 32 },
      { month: 'Sep', registered: 185, selected: 33 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 200 },
      { branch: 'ECE', count: 120 },
      { branch: 'Mechanical', count: 100 },
      { branch: 'Civil', count: 90 },
    ],
  },
  {
    id: 'dist-ckm',
    district: 'Chikkamagaluru',
    zone: 'Central',
    collegesCount: 4,
    drivesCount: 2,
    studentsRegistered: 420,
    studentsExamAppeared: 380,
    studentsQualified: 230,
    studentsSelected: 72,
    offersAccepted: 66,
    joiningConfirmed: 56,
    selectionRate: 18.9,
    offerAcceptanceRate: 91.7,
    activeHRExecutives: 1,
    topColleges: ['Adichunchanagiri Institute of Technology (AIT)'],
    growthYoY: 12.0,
    monthlyTrends: [
      { month: 'Jun', registered: 35, selected: 6 },
      { month: 'Jul', registered: 85, selected: 15 },
      { month: 'Aug', registered: 145, selected: 25 },
      { month: 'Sep', registered: 155, selected: 26 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 170 },
      { branch: 'ECE', count: 100 },
      { branch: 'Civil', count: 80 },
      { branch: 'Mechanical', count: 70 },
    ],
  },
  {
    id: 'dist-bgk',
    district: 'Bagalkote',
    zone: 'North',
    collegesCount: 5,
    drivesCount: 2,
    studentsRegistered: 480,
    studentsExamAppeared: 430,
    studentsQualified: 260,
    studentsSelected: 78,
    offersAccepted: 72,
    joiningConfirmed: 62,
    selectionRate: 18.1,
    offerAcceptanceRate: 92.3,
    activeHRExecutives: 1,
    topColleges: ['Basaveshwar Engineering College (BEC Bagalkote)'],
    growthYoY: 20.5,
    monthlyTrends: [
      { month: 'Jun', registered: 40, selected: 7 },
      { month: 'Jul', registered: 95, selected: 16 },
      { month: 'Aug', registered: 165, selected: 27 },
      { month: 'Sep', registered: 180, selected: 28 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 190 },
      { branch: 'Mechanical', count: 110 },
      { branch: 'Civil', count: 100 },
      { branch: 'ECE', count: 80 },
    ],
  },
  {
    id: 'dist-vjp',
    district: 'Vijayapura',
    zone: 'North',
    collegesCount: 4,
    drivesCount: 2,
    studentsRegistered: 390,
    studentsExamAppeared: 350,
    studentsQualified: 200,
    studentsSelected: 60,
    offersAccepted: 55,
    joiningConfirmed: 48,
    selectionRate: 17.1,
    offerAcceptanceRate: 91.7,
    activeHRExecutives: 1,
    topColleges: ['BLDEA V.P. Dr. P.G. Halakatti College of Engg'],
    growthYoY: 17.6,
    monthlyTrends: [
      { month: 'Jun', registered: 30, selected: 5 },
      { month: 'Jul', registered: 80, selected: 12 },
      { month: 'Aug', registered: 135, selected: 21 },
      { month: 'Sep', registered: 145, selected: 22 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 160 },
      { branch: 'Civil', count: 90 },
      { branch: 'Mechanical', count: 80 },
      { branch: 'ECE', count: 60 },
    ],
  },
  {
    id: 'dist-rcr',
    district: 'Raichur',
    zone: 'North',
    collegesCount: 3,
    drivesCount: 1,
    studentsRegistered: 280,
    studentsExamAppeared: 250,
    studentsQualified: 140,
    studentsSelected: 40,
    offersAccepted: 37,
    joiningConfirmed: 32,
    selectionRate: 16.0,
    offerAcceptanceRate: 92.5,
    activeHRExecutives: 1,
    topColleges: ['Navodaya Institute of Technology'],
    growthYoY: 26.2,
    monthlyTrends: [
      { month: 'Jun', registered: 20, selected: 3 },
      { month: 'Jul', registered: 60, selected: 9 },
      { month: 'Aug', registered: 95, selected: 14 },
      { month: 'Sep', registered: 105, selected: 14 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 110 },
      { branch: 'ECE', count: 70 },
      { branch: 'Civil', count: 55 },
      { branch: 'Mechanical', count: 45 },
    ],
  },
  {
    id: 'dist-bdr',
    district: 'Bidar',
    zone: 'North',
    collegesCount: 3,
    drivesCount: 1,
    studentsRegistered: 260,
    studentsExamAppeared: 230,
    studentsQualified: 125,
    studentsSelected: 36,
    offersAccepted: 33,
    joiningConfirmed: 28,
    selectionRate: 15.7,
    offerAcceptanceRate: 91.7,
    activeHRExecutives: 1,
    topColleges: ['Guru Nanak Dev Engineering College Bidar'],
    growthYoY: 22.0,
    monthlyTrends: [
      { month: 'Jun', registered: 20, selected: 3 },
      { month: 'Jul', registered: 55, selected: 8 },
      { month: 'Aug', registered: 90, selected: 12 },
      { month: 'Sep', registered: 95, selected: 13 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 105 },
      { branch: 'ECE', count: 65 },
      { branch: 'Mechanical', count: 50 },
      { branch: 'Civil', count: 40 },
    ],
  },
  {
    id: 'dist-kpl',
    district: 'Koppal',
    zone: 'North',
    collegesCount: 2,
    drivesCount: 1,
    studentsRegistered: 190,
    studentsExamAppeared: 170,
    studentsQualified: 90,
    studentsSelected: 25,
    offersAccepted: 23,
    joiningConfirmed: 20,
    selectionRate: 14.7,
    offerAcceptanceRate: 92.0,
    activeHRExecutives: 1,
    topColleges: ['Government Engineering College Gangavathi'],
    growthYoY: 35.0,
    monthlyTrends: [
      { month: 'Jun', registered: 15, selected: 2 },
      { month: 'Jul', registered: 40, selected: 5 },
      { month: 'Aug', registered: 65, selected: 9 },
      { month: 'Sep', registered: 70, selected: 9 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 80 },
      { branch: 'ECE', count: 45 },
      { branch: 'Mechanical', count: 35 },
      { branch: 'Civil', count: 30 },
    ],
  },
  {
    id: 'dist-gdg',
    district: 'Gadag',
    zone: 'North',
    collegesCount: 2,
    drivesCount: 1,
    studentsRegistered: 180,
    studentsExamAppeared: 160,
    studentsQualified: 88,
    studentsSelected: 26,
    offersAccepted: 24,
    joiningConfirmed: 20,
    selectionRate: 16.3,
    offerAcceptanceRate: 92.3,
    activeHRExecutives: 1,
    topColleges: ['Government Engineering College Huvina Hadagali border / Gadag'],
    growthYoY: 18.0,
    monthlyTrends: [
      { month: 'Jun', registered: 15, selected: 2 },
      { month: 'Jul', registered: 35, selected: 5 },
      { month: 'Aug', registered: 60, selected: 9 },
      { month: 'Sep', registered: 70, selected: 10 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 75 },
      { branch: 'ECE', count: 45 },
      { branch: 'Mechanical', count: 35 },
      { branch: 'Civil', count: 25 },
    ],
  },
  {
    id: 'dist-uk',
    district: 'Uttara Kannada',
    zone: 'Coastal',
    collegesCount: 3,
    drivesCount: 1,
    studentsRegistered: 260,
    studentsExamAppeared: 235,
    studentsQualified: 145,
    studentsSelected: 48,
    offersAccepted: 44,
    joiningConfirmed: 38,
    selectionRate: 20.4,
    offerAcceptanceRate: 91.7,
    activeHRExecutives: 1,
    topColleges: ['Government Engineering College Karwar', 'Anjuman Institute Bhatkal'],
    growthYoY: 15.5,
    monthlyTrends: [
      { month: 'Jun', registered: 20, selected: 4 },
      { month: 'Jul', registered: 55, selected: 10 },
      { month: 'Aug', registered: 90, selected: 16 },
      { month: 'Sep', registered: 95, selected: 18 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 110 },
      { branch: 'ECE', count: 65 },
      { branch: 'Civil', count: 45 },
      { branch: 'Mechanical', count: 40 },
    ],
  },
  {
    id: 'dist-hvr',
    district: 'Haveri',
    zone: 'Central',
    collegesCount: 3,
    drivesCount: 1,
    studentsRegistered: 240,
    studentsExamAppeared: 215,
    studentsQualified: 120,
    studentsSelected: 34,
    offersAccepted: 31,
    joiningConfirmed: 26,
    selectionRate: 15.8,
    offerAcceptanceRate: 91.2,
    activeHRExecutives: 1,
    topColleges: ['Government Engineering College Haveri'],
    growthYoY: 16.5,
    monthlyTrends: [
      { month: 'Jun', registered: 20, selected: 3 },
      { month: 'Jul', registered: 50, selected: 7 },
      { month: 'Aug', registered: 85, selected: 12 },
      { month: 'Sep', registered: 85, selected: 12 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 100 },
      { branch: 'ECE', count: 60 },
      { branch: 'Mechanical', count: 45 },
      { branch: 'Civil', count: 35 },
    ],
  },
  {
    id: 'dist-cta',
    district: 'Chitradurga',
    zone: 'Central',
    collegesCount: 3,
    drivesCount: 1,
    studentsRegistered: 290,
    studentsExamAppeared: 260,
    studentsQualified: 145,
    studentsSelected: 42,
    offersAccepted: 38,
    joiningConfirmed: 32,
    selectionRate: 16.2,
    offerAcceptanceRate: 90.5,
    activeHRExecutives: 1,
    topColleges: ['SJM Institute of Technology Chitradurga'],
    growthYoY: 19.8,
    monthlyTrends: [
      { month: 'Jun', registered: 25, selected: 3 },
      { month: 'Jul', registered: 60, selected: 9 },
      { month: 'Aug', registered: 100, selected: 15 },
      { month: 'Sep', registered: 105, selected: 15 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 120 },
      { branch: 'ECE', count: 70 },
      { branch: 'Civil', count: 55 },
      { branch: 'Mechanical', count: 45 },
    ],
  },
  {
    id: 'dist-cbp',
    district: 'Chikkaballapura',
    zone: 'Bengaluru Metro',
    collegesCount: 4,
    drivesCount: 2,
    studentsRegistered: 360,
    studentsExamAppeared: 320,
    studentsQualified: 190,
    studentsSelected: 58,
    offersAccepted: 53,
    joiningConfirmed: 45,
    selectionRate: 18.1,
    offerAcceptanceRate: 91.4,
    activeHRExecutives: 1,
    topColleges: ['SJCIT (S J C Institute of Technology Chikkaballapur)'],
    growthYoY: 22.0,
    monthlyTrends: [
      { month: 'Jun', registered: 30, selected: 5 },
      { month: 'Jul', registered: 75, selected: 12 },
      { month: 'Aug', registered: 125, selected: 20 },
      { month: 'Sep', registered: 130, selected: 21 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 150 },
      { branch: 'ECE', count: 90 },
      { branch: 'Mechanical', count: 65 },
      { branch: 'Civil', count: 55 },
    ],
  },
  {
    id: 'dist-klr',
    district: 'Kolar',
    zone: 'South',
    collegesCount: 4,
    drivesCount: 2,
    studentsRegistered: 340,
    studentsExamAppeared: 305,
    studentsQualified: 180,
    studentsSelected: 52,
    offersAccepted: 48,
    joiningConfirmed: 40,
    selectionRate: 17.0,
    offerAcceptanceRate: 92.3,
    activeHRExecutives: 1,
    topColleges: ['C. Abdul Hakeem Extension / Golden Valley Engg'],
    growthYoY: 14.5,
    monthlyTrends: [
      { month: 'Jun', registered: 30, selected: 4 },
      { month: 'Jul', registered: 70, selected: 11 },
      { month: 'Aug', registered: 120, selected: 18 },
      { month: 'Sep', registered: 120, selected: 19 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 140 },
      { branch: 'ECE', count: 85 },
      { branch: 'Mechanical', count: 60 },
      { branch: 'Civil', count: 55 },
    ],
  },
  {
    id: 'dist-rmn',
    district: 'Ramanagara',
    zone: 'Bengaluru Metro',
    collegesCount: 4,
    drivesCount: 2,
    studentsRegistered: 380,
    studentsExamAppeared: 340,
    studentsQualified: 210,
    studentsSelected: 64,
    offersAccepted: 59,
    joiningConfirmed: 50,
    selectionRate: 18.8,
    offerAcceptanceRate: 92.2,
    activeHRExecutives: 1,
    topColleges: ['Ghousia College of Engineering Ramanagara'],
    growthYoY: 16.0,
    monthlyTrends: [
      { month: 'Jun', registered: 35, selected: 6 },
      { month: 'Jul', registered: 80, selected: 13 },
      { month: 'Aug', registered: 130, selected: 22 },
      { month: 'Sep', registered: 135, selected: 23 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 160 },
      { branch: 'Mechanical', count: 90 },
      { branch: 'ECE', count: 75 },
      { branch: 'Civil', count: 55 },
    ],
  },
  {
    id: 'dist-kdg',
    district: 'Kodagu',
    zone: 'South',
    collegesCount: 2,
    drivesCount: 1,
    studentsRegistered: 170,
    studentsExamAppeared: 155,
    studentsQualified: 95,
    studentsSelected: 30,
    offersAccepted: 28,
    joiningConfirmed: 24,
    selectionRate: 19.4,
    offerAcceptanceRate: 93.3,
    activeHRExecutives: 1,
    topColleges: ['Coorg Institute of Technology (CIT Ponnampet)'],
    growthYoY: 13.0,
    monthlyTrends: [
      { month: 'Jun', registered: 15, selected: 3 },
      { month: 'Jul', registered: 35, selected: 6 },
      { month: 'Aug', registered: 60, selected: 10 },
      { month: 'Sep', registered: 60, selected: 11 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 70 },
      { branch: 'ECE', count: 45 },
      { branch: 'Civil', count: 30 },
      { branch: 'Mechanical', count: 25 },
    ],
  },
  {
    id: 'dist-cmr',
    district: 'Chamarajanagar',
    zone: 'South',
    collegesCount: 2,
    drivesCount: 1,
    studentsRegistered: 160,
    studentsExamAppeared: 140,
    studentsQualified: 75,
    studentsSelected: 22,
    offersAccepted: 20,
    joiningConfirmed: 18,
    selectionRate: 15.7,
    offerAcceptanceRate: 90.9,
    activeHRExecutives: 1,
    topColleges: ['Government Engineering College Chamarajanagar'],
    growthYoY: 28.0,
    monthlyTrends: [
      { month: 'Jun', registered: 15, selected: 2 },
      { month: 'Jul', registered: 30, selected: 4 },
      { month: 'Aug', registered: 55, selected: 8 },
      { month: 'Sep', registered: 60, selected: 8 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 65 },
      { branch: 'Civil', count: 40 },
      { branch: 'Mechanical', count: 30 },
      { branch: 'ECE', count: 25 },
    ],
  },
  {
    id: 'dist-ydg',
    district: 'Yadgir',
    zone: 'North',
    collegesCount: 1,
    drivesCount: 1,
    studentsRegistered: 120,
    studentsExamAppeared: 105,
    studentsQualified: 52,
    studentsSelected: 15,
    offersAccepted: 14,
    joiningConfirmed: 12,
    selectionRate: 14.3,
    offerAcceptanceRate: 93.3,
    activeHRExecutives: 1,
    topColleges: ['Government Engineering College Yadgir'],
    growthYoY: 42.0,
    monthlyTrends: [
      { month: 'Jun', registered: 10, selected: 1 },
      { month: 'Jul', registered: 25, selected: 3 },
      { month: 'Aug', registered: 40, selected: 5 },
      { month: 'Sep', registered: 45, selected: 6 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 50 },
      { branch: 'Civil', count: 30 },
      { branch: 'Mechanical', count: 25 },
      { branch: 'ECE', count: 15 },
    ],
  },
  {
    id: 'dist-vjr',
    district: 'Vijayanagara',
    zone: 'North',
    collegesCount: 2,
    drivesCount: 1,
    studentsRegistered: 170,
    studentsExamAppeared: 150,
    studentsQualified: 80,
    studentsSelected: 24,
    offersAccepted: 22,
    joiningConfirmed: 19,
    selectionRate: 16.0,
    offerAcceptanceRate: 91.7,
    activeHRExecutives: 1,
    topColleges: ['Government Engineering College Hagaribommanahalli / Hosapete'],
    growthYoY: 34.0,
    monthlyTrends: [
      { month: 'Jun', registered: 15, selected: 2 },
      { month: 'Jul', registered: 35, selected: 5 },
      { month: 'Aug', registered: 60, selected: 8 },
      { month: 'Sep', registered: 60, selected: 9 },
    ],
    branchBreakdown: [
      { branch: 'CSE', count: 70 },
      { branch: 'ECE', count: 40 },
      { branch: 'Mechanical', count: 35 },
      { branch: 'Civil', count: 25 },
    ],
  },
];

// =========================================================================
// 2. EXECUTIVE RECRUITMENT PIPELINE FUNNEL (POWER BI SPEC)
// =========================================================================
export const PIPELINE_FUNNEL: PipelineFunnelStage[] = [
  { id: 'stg-reg', stageName: 'Registered', count: 21850, dropOffCount: 2010, conversionRate: 100.0, benchmarkRate: 100.0, color: '#001B4D' },
  { id: 'stg-ver', stageName: 'Profile Verified', count: 19840, dropOffCount: 2110, conversionRate: 90.8, benchmarkRate: 88.0, color: '#002B66' },
  { id: 'stg-ex-app', stageName: 'Exam Appeared', count: 17730, dropOffCount: 6510, conversionRate: 81.1, benchmarkRate: 75.0, color: '#004080' },
  { id: 'stg-ex-qual', stageName: 'Exam Qualified', count: 11220, dropOffCount: 3740, conversionRate: 51.4, benchmarkRate: 48.0, color: '#005BBB' },
  { id: 'stg-int-eval', stageName: 'Interview Conducted', count: 7480, dropOffCount: 2980, conversionRate: 34.2, benchmarkRate: 30.0, color: '#0077D6' },
  { id: 'stg-selected', stageName: 'HR Selected', count: 4500, dropOffCount: 160, conversionRate: 20.6, benchmarkRate: 18.5, color: '#0094F2' },
  { id: 'stg-off-sent', stageName: 'Offer Dispatched', count: 4340, dropOffCount: 345, conversionRate: 19.9, benchmarkRate: 18.0, color: '#14B8FF' },
  { id: 'stg-off-acc', stageName: 'Offer Accepted', count: 3995, dropOffCount: 520, conversionRate: 18.3, benchmarkRate: 16.5, color: '#00C896' },
  { id: 'stg-joined', stageName: 'Joining Confirmed', count: 3475, dropOffCount: 0, conversionRate: 15.9, benchmarkRate: 14.0, color: '#10B981' },
];

// =========================================================================
// 3. COLLEGE PERFORMANCE & LEADERBOARD (ALL INSTITUTION TYPES)
// =========================================================================
export const COLLEGE_PERFORMANCE_METRICS: CollegePerformanceStats[] = [
  {
    id: 'cpm-01',
    collegeId: 'col-001',
    collegeName: 'R.V. College of Engineering (RVCE)',
    district: 'Bengaluru Urban',
    tier: 'Tier-1',
    type: 'Autonomous',
    studentsRegistered: 840,
    examCompletionRate: 96.2,
    selectionRate: 32.5,
    offerAcceptanceRate: 94.8,
    joiningRate: 89.2,
    drivesCount: 6,
    rank: 1,
    previousYearSelected: 230,
    currentYearSelected: 273,
    growthPct: 18.7,
  },
  {
    id: 'cpm-02',
    collegeId: 'col-002',
    collegeName: 'B.M.S. College of Engineering (BMSCE)',
    district: 'Bengaluru Urban',
    tier: 'Tier-1',
    type: 'Autonomous',
    studentsRegistered: 790,
    examCompletionRate: 94.5,
    selectionRate: 30.8,
    offerAcceptanceRate: 93.6,
    joiningRate: 88.0,
    drivesCount: 5,
    rank: 2,
    previousYearSelected: 210,
    currentYearSelected: 243,
    growthPct: 15.7,
  },
  {
    id: 'cpm-03',
    collegeId: 'col-003',
    collegeName: 'Ramaiah Institute of Technology (MSRIT)',
    district: 'Bengaluru Urban',
    tier: 'Tier-1',
    type: 'Autonomous',
    studentsRegistered: 720,
    examCompletionRate: 93.8,
    selectionRate: 29.4,
    offerAcceptanceRate: 92.9,
    joiningRate: 87.5,
    drivesCount: 5,
    rank: 3,
    previousYearSelected: 185,
    currentYearSelected: 212,
    growthPct: 14.6,
  },
  {
    id: 'cpm-04',
    collegeId: 'col-007',
    collegeName: 'The National Institute of Engineering (NIE)',
    district: 'Mysuru',
    tier: 'Tier-1',
    type: 'Autonomous',
    studentsRegistered: 620,
    examCompletionRate: 92.5,
    selectionRate: 27.8,
    offerAcceptanceRate: 93.2,
    joiningRate: 86.4,
    drivesCount: 4,
    rank: 4,
    previousYearSelected: 148,
    currentYearSelected: 172,
    growthPct: 16.2,
  },
  {
    id: 'cpm-05',
    collegeId: 'col-005',
    collegeName: 'Siddaganga Institute of Technology (SIT Tumkur)',
    district: 'Tumakuru',
    tier: 'Tier-1',
    type: 'Autonomous',
    studentsRegistered: 590,
    examCompletionRate: 91.0,
    selectionRate: 26.2,
    offerAcceptanceRate: 92.0,
    joiningRate: 85.0,
    drivesCount: 4,
    rank: 5,
    previousYearSelected: 132,
    currentYearSelected: 155,
    growthPct: 17.4,
  },
  {
    id: 'cpm-06',
    collegeId: 'col-008',
    collegeName: 'KLS Gogte Institute of Technology',
    district: 'Belagavi',
    tier: 'Tier-1',
    type: 'Autonomous',
    studentsRegistered: 540,
    examCompletionRate: 90.2,
    selectionRate: 25.1,
    offerAcceptanceRate: 93.8,
    joiningRate: 84.5,
    drivesCount: 4,
    rank: 6,
    previousYearSelected: 110,
    currentYearSelected: 136,
    growthPct: 23.6,
  },
  {
    id: 'cpm-07',
    collegeId: 'col-009',
    collegeName: 'SDM College of Engineering & Technology',
    district: 'Dharwad',
    tier: 'Tier-2',
    type: 'Autonomous',
    studentsRegistered: 480,
    examCompletionRate: 89.5,
    selectionRate: 24.5,
    offerAcceptanceRate: 92.5,
    joiningRate: 83.0,
    drivesCount: 3,
    rank: 7,
    previousYearSelected: 95,
    currentYearSelected: 118,
    growthPct: 24.2,
  },
  {
    id: 'cpm-08',
    collegeId: 'col-010',
    collegeName: 'NMAM Institute of Technology (Nitte)',
    district: 'Udupi',
    tier: 'Tier-1',
    type: 'Deemed University',
    studentsRegistered: 490,
    examCompletionRate: 92.0,
    selectionRate: 27.5,
    offerAcceptanceRate: 93.0,
    joiningRate: 85.2,
    drivesCount: 3,
    rank: 8,
    previousYearSelected: 112,
    currentYearSelected: 135,
    growthPct: 20.5,
  },
  {
    id: 'cpm-09',
    collegeId: 'col-011',
    collegeName: 'Canara Engineering College',
    district: 'Dakshina Kannada',
    tier: 'Tier-2',
    type: 'VTU Affiliated',
    studentsRegistered: 460,
    examCompletionRate: 91.2,
    selectionRate: 25.8,
    offerAcceptanceRate: 92.4,
    joiningRate: 84.0,
    drivesCount: 3,
    rank: 9,
    previousYearSelected: 96,
    currentYearSelected: 119,
    growthPct: 23.9,
  },
  {
    id: 'cpm-10',
    collegeId: 'col-012',
    collegeName: 'Bapuji Institute of Engineering and Technology (BIET)',
    district: 'Davanagere',
    tier: 'Tier-2',
    type: 'VTU Affiliated',
    studentsRegistered: 430,
    examCompletionRate: 88.5,
    selectionRate: 22.8,
    offerAcceptanceRate: 91.5,
    joiningRate: 82.5,
    drivesCount: 3,
    rank: 10,
    previousYearSelected: 80,
    currentYearSelected: 98,
    growthPct: 22.5,
  },
  {
    id: 'cpm-11',
    collegeId: 'col-013',
    collegeName: 'Basaveshwar Engineering College (BEC Bagalkote)',
    district: 'Bagalkote',
    tier: 'Tier-2',
    type: 'Autonomous',
    studentsRegistered: 390,
    examCompletionRate: 89.0,
    selectionRate: 21.0,
    offerAcceptanceRate: 92.0,
    joiningRate: 81.0,
    drivesCount: 2,
    rank: 11,
    previousYearSelected: 68,
    currentYearSelected: 82,
    growthPct: 20.6,
  },
  {
    id: 'cpm-12',
    collegeId: 'col-014',
    collegeName: 'Malnad College of Engineering (MCE Hassan)',
    district: 'Hassan',
    tier: 'Tier-2',
    type: 'Autonomous',
    studentsRegistered: 410,
    examCompletionRate: 88.0,
    selectionRate: 22.4,
    offerAcceptanceRate: 91.8,
    joiningRate: 82.0,
    drivesCount: 2,
    rank: 12,
    previousYearSelected: 75,
    currentYearSelected: 92,
    growthPct: 22.7,
  },
  {
    id: 'cpm-13',
    collegeId: 'col-015',
    collegeName: 'Government Engineering College Karwar',
    district: 'Uttara Kannada',
    tier: 'Tier-3',
    type: 'Government Engineering College',
    studentsRegistered: 260,
    examCompletionRate: 86.5,
    selectionRate: 20.4,
    offerAcceptanceRate: 91.7,
    joiningRate: 80.0,
    drivesCount: 1,
    rank: 13,
    previousYearSelected: 38,
    currentYearSelected: 53,
    growthPct: 39.5,
  },
  {
    id: 'cpm-14',
    collegeId: 'col-016',
    collegeName: 'Government Engineering College Chamarajanagar',
    district: 'Chamarajanagar',
    tier: 'Tier-3',
    type: 'Government Engineering College',
    studentsRegistered: 160,
    examCompletionRate: 87.5,
    selectionRate: 15.7,
    offerAcceptanceRate: 90.9,
    joiningRate: 81.8,
    drivesCount: 1,
    rank: 14,
    previousYearSelected: 15,
    currentYearSelected: 25,
    growthPct: 66.7,
  },
];

// =========================================================================
// 4. HR PERFORMANCE & PRODUCTIVITY LEADERBOARD
// =========================================================================
export const HR_PERFORMANCE_METRICS: HRPerformanceStats[] = [
  {
    id: 'hr-perf-01',
    hrId: 'usr-hr-01',
    hrName: 'Hitha, Kusuma',
    email: '[EMAIL_ADDRESS]',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    assignedColleges: 24,
    callsCompleted: 348,
    followUpsCompleted: 192,
    studentsReviewed: 1420,
    interviewsConducted: 885,
    selectedCount: 512,
    selectionRate: 57.8,
    offerAcceptanceRate: 94.2,
    avgResponseTimeHours: 1.4,
    escalations: 1,
    avgInterviewRating: 4.8,
    weeklyProductivity: [
      { week: 'Wk 1', calls: 78, interviews: 195, selections: 110 },
      { week: 'Wk 2', calls: 92, interviews: 220, selections: 135 },
      { week: 'Wk 3', calls: 86, interviews: 235, selections: 140 },
      { week: 'Wk 4', calls: 92, interviews: 235, selections: 127 },
    ],
  },
  {
    id: 'hr-perf-02',
    hrId: 'usr-hr-02',
    hrName: 'Divya.H',
    email: '[EMAIL_ADDRESS]',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    assignedColleges: 22,
    callsCompleted: 312,
    followUpsCompleted: 184,
    studentsReviewed: 1280,
    interviewsConducted: 810,
    selectedCount: 468,
    selectionRate: 57.7,
    offerAcceptanceRate: 93.8,
    avgResponseTimeHours: 1.8,
    escalations: 2,
    avgInterviewRating: 4.7,
    weeklyProductivity: [
      { week: 'Wk 1', calls: 70, interviews: 180, selections: 102 },
      { week: 'Wk 2', calls: 82, interviews: 205, selections: 118 },
      { week: 'Wk 3', calls: 80, interviews: 215, selections: 126 },
      { week: 'Wk 4', calls: 80, interviews: 210, selections: 122 },
    ],
  },
  {
    id: 'hr-perf-03',
    hrId: 'usr-hr-03',
    hrName: 'Priya Nair',
    email: '[EMAIL_ADDRESS]',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    assignedColleges: 18,
    callsCompleted: 265,
    followUpsCompleted: 156,
    studentsReviewed: 1150,
    interviewsConducted: 740,
    selectedCount: 418,
    selectionRate: 56.5,
    offerAcceptanceRate: 92.6,
    avgResponseTimeHours: 2.1,
    escalations: 2,
    avgInterviewRating: 4.6,
    weeklyProductivity: [
      { week: 'Wk 1', calls: 62, interviews: 165, selections: 95 },
      { week: 'Wk 2', calls: 68, interviews: 190, selections: 105 },
      { week: 'Wk 3', calls: 70, interviews: 195, selections: 112 },
      { week: 'Wk 4', calls: 65, interviews: 190, selections: 106 },
    ],
  },
  {
    id: 'hr-perf-04',
    hrId: 'usr-hr-04',
    hrName: 'Rajesh V',
    email: '[EMAIL_ADDRESS]',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    assignedColleges: 16,
    callsCompleted: 240,
    followUpsCompleted: 142,
    studentsReviewed: 980,
    interviewsConducted: 650,
    selectedCount: 360,
    selectionRate: 55.4,
    offerAcceptanceRate: 91.5,
    avgResponseTimeHours: 2.4,
    escalations: 3,
    avgInterviewRating: 4.5,
    weeklyProductivity: [
      { week: 'Wk 1', calls: 55, interviews: 150, selections: 82 },
      { week: 'Wk 2', calls: 62, interviews: 170, selections: 94 },
      { week: 'Wk 3', calls: 65, interviews: 170, selections: 96 },
      { week: 'Wk 4', calls: 58, interviews: 160, selections: 88 },
    ],
  },
  {
    id: 'hr-perf-05',
    hrId: 'usr-hr-05',
    hrName: 'Karthik Rao',
    email: '[EMAIL_ADDRESS]',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    assignedColleges: 14,
    callsCompleted: 210,
    followUpsCompleted: 128,
    studentsReviewed: 860,
    interviewsConducted: 560,
    selectedCount: 310,
    selectionRate: 55.3,
    offerAcceptanceRate: 91.0,
    avgResponseTimeHours: 2.6,
    escalations: 3,
    avgInterviewRating: 4.5,
    weeklyProductivity: [
      { week: 'Wk 1', calls: 48, interviews: 130, selections: 70 },
      { week: 'Wk 2', calls: 54, interviews: 145, selections: 82 },
      { week: 'Wk 3', calls: 56, interviews: 150, selections: 84 },
      { week: 'Wk 4', calls: 52, interviews: 135, selections: 74 },
    ],
  },
];

// =========================================================================
// 5. GQT COURSES & BATCH ANALYTICS
// =========================================================================
export const GQT_COURSES_ANALYTICS: CourseAnalyticsData[] = [
  {
    id: 'crs-01',
    courseName: 'Agentic AI Java Full Stack',
    shortCode: 'AI-JAVA',
    registrations: 8420,
    qualified: 4320,
    selections: 1750,
    accepted: 1580,
    batchCapacity: 1800,
    batchFilled: 1580,
    completionForecastDays: 14,
    color: '#005BBB',
  },
  {
    id: 'crs-02',
    courseName: 'Agentic AI Python Full Stack',
    shortCode: 'AI-PY',
    registrations: 6150,
    qualified: 3180,
    selections: 1280,
    accepted: 1160,
    batchCapacity: 1300,
    batchFilled: 1160,
    completionForecastDays: 18,
    color: '#14B8FF',
  },
  {
    id: 'crs-03',
    courseName: 'Agentic AI MERN Full Stack',
    shortCode: 'AI-MERN',
    registrations: 3820,
    qualified: 1960,
    selections: 780,
    accepted: 705,
    batchCapacity: 800,
    batchFilled: 705,
    completionForecastDays: 21,
    color: '#7C3AED',
  },
  {
    id: 'crs-04',
    courseName: 'Software Testing Full Stack',
    shortCode: 'TESTING',
    registrations: 2120,
    qualified: 1080,
    selections: 440,
    accepted: 395,
    batchCapacity: 450,
    batchFilled: 395,
    completionForecastDays: 12,
    color: '#F59E0B',
  },
  {
    id: 'crs-05',
    courseName: 'Data Analytics & Power BI',
    shortCode: 'DATA-BI',
    registrations: 1980,
    qualified: 980,
    selections: 390,
    accepted: 350,
    batchCapacity: 400,
    batchFilled: 350,
    completionForecastDays: 24,
    color: '#10B981',
  },
  {
    id: 'crs-06',
    courseName: 'Data Science & Generative AI',
    shortCode: 'DS-GENAI',
    registrations: 1460,
    qualified: 720,
    selections: 290,
    accepted: 260,
    batchCapacity: 300,
    batchFilled: 260,
    completionForecastDays: 28,
    color: '#EC4899',
  },
];

export const BRANCH_ANALYTICS: BranchAnalyticsData[] = [
  { branch: 'Computer Science & Engineering', code: 'CSE', registrations: 9680, selections: 2120, acceptanceRate: 94.2, topDistricts: ['Bengaluru Urban', 'Mysuru', 'Dakshina Kannada'] },
  { branch: 'Information Science & Engineering', code: 'ISE', registrations: 4120, selections: 910, acceptanceRate: 93.5, topDistricts: ['Bengaluru Urban', 'Tumakuru', 'Udupi'] },
  { branch: 'Electronics & Communication', code: 'ECE', registrations: 3850, selections: 790, acceptanceRate: 92.1, topDistricts: ['Belagavi', 'Dharwad', 'Bengaluru Urban'] },
  { branch: 'Electrical & Electronics', code: 'EEE', registrations: 1240, selections: 240, acceptanceRate: 91.0, topDistricts: ['Shivamogga', 'Davanagere', 'Mysuru'] },
  { branch: 'Mechanical Engineering', code: 'MECH', registrations: 1180, selections: 195, acceptanceRate: 89.8, topDistricts: ['Belagavi', 'Bagalkote', 'Ballari'] },
  { branch: 'Civil Engineering', code: 'CIVIL', registrations: 890, selections: 125, acceptanceRate: 88.5, topDistricts: ['Kalaburagi', 'Vijayapura', 'Raichur'] },
  { branch: 'Master of Computer Applications', code: 'MCA', registrations: 540, selections: 110, acceptanceRate: 93.0, topDistricts: ['Bengaluru Urban', 'Dakshina Kannada'] },
  { branch: 'Bachelor of Computer Applications', code: 'BCA', registrations: 350, selections: 70, acceptanceRate: 90.0, topDistricts: ['Bengaluru Urban', 'Mysuru'] },
];

export const PASSING_YEAR_ANALYTICS = [
  { year: '2026', registrations: 14250, examAppeared: 11800, selections: 2980, offersAccepted: 2710 },
  { year: '2025', registrations: 5420, examAppeared: 4320, selections: 1040, offersAccepted: 940 },
  { year: '2027', registrations: 1680, examAppeared: 1240, selections: 380, offersAccepted: 345 },
  { year: '2028', registrations: 500, examAppeared: 370, selections: 100, offersAccepted: 0 },
];

export const TRAINING_BATCHES: TrainingBatchMetric[] = [
  {
    id: 'btc-01',
    batchName: 'Agentic AI Java Batch-A (BLR HQ)',
    course: 'Agentic AI Java Full Stack',
    capacity: 250,
    filled: 242,
    available: 8,
    joiningRate: 96.8,
    trainer: 'Sudhir Gowda (Principal Architect)',
    location: 'GQT Tech Park, BTM 2nd Stage, Bengaluru',
    mode: 'Offline',
    progressPct: 35,
    startDate: '01-Aug-2026',
    status: 'In Progress',
  },
  {
    id: 'btc-02',
    batchName: 'Agentic AI Java Batch-B (Hybrid Hub)',
    course: 'Agentic AI Java Full Stack',
    capacity: 300,
    filled: 288,
    available: 12,
    joiningRate: 96.0,
    trainer: 'Harish M (Lead Instructor)',
    location: 'GQT Virtual Campus + Bengaluru Campus',
    mode: 'Hybrid',
    progressPct: 15,
    startDate: '15-Aug-2026',
    status: 'In Progress',
  },
  {
    id: 'btc-03',
    batchName: 'Agentic AI Python Batch-A (Mysuru Campus)',
    course: 'Agentic AI Python Full Stack',
    capacity: 200,
    filled: 194,
    available: 6,
    joiningRate: 97.0,
    trainer: 'Divyashree K (Senior AI Mentor)',
    location: 'NIE Campus Auditorium & GQT Hub, Mysuru',
    mode: 'Hybrid',
    progressPct: 20,
    startDate: '01-Aug-2026',
    status: 'In Progress',
  },
  {
    id: 'btc-04',
    batchName: 'Software Testing Batch-A (North Karnataka Hub)',
    course: 'Software Testing Full Stack',
    capacity: 150,
    filled: 142,
    available: 8,
    joiningRate: 94.6,
    trainer: 'Vinay Kumar (Automation Lead)',
    location: 'SDMCET Campus, Dharwad / Online',
    mode: 'Online',
    progressPct: 40,
    startDate: '10-Jul-2026',
    status: 'In Progress',
  },
  {
    id: 'btc-05',
    batchName: 'Data Analytics & Power BI Batch-A',
    course: 'Data Analytics & Power BI',
    capacity: 180,
    filled: 165,
    available: 15,
    joiningRate: 91.6,
    trainer: 'Pooja Hegde (Analytics Director)',
    location: 'GQT Virtual Campus',
    mode: 'Online',
    progressPct: 10,
    startDate: '20-Aug-2026',
    status: 'Enrolling',
  },
];

// =========================================================================
// 6. EXECUTIVE SAVED REPORTS (BOARD CONFIDENTIAL & REGULATORY)
// =========================================================================
export const SAVED_EXECUTIVE_REPORTS: ExecutiveSavedReport[] = [
  {
    id: 'rpt-mgmt-01',
    title: 'GQT CSR State-Wide Drive Impact & Hiring Performance Q3',
    category: 'Executive',
    frequency: 'Monthly',
    generatedDate: '2026-09-24T18:30:00Z',
    nextScheduled: '2026-10-24T00:00:00Z',
    format: 'PDF',
    fileSize: '4.8 MB',
    recipients: ['director@globalquesttechnologies.com', 'board@globalquesttechnologies.com'],
    version: 'v3.2',
    isBoardConfidential: true,
  },
  {
    id: 'rpt-mgmt-02',
    title: '31 Karnataka Districts Rural Upliftment & Academic Equity Audit',
    category: 'District',
    frequency: 'Quarterly',
    generatedDate: '2026-09-20T12:00:00Z',
    nextScheduled: '2026-12-20T00:00:00Z',
    format: 'Excel',
    fileSize: '8.4 MB',
    recipients: ['csr.lead@globalquesttechnologies.com', 'operations@globalquesttechnologies.com'],
    version: 'v2.1',
    isBoardConfidential: false,
  },
  {
    id: 'rpt-mgmt-03',
    title: 'College Conversion Leaderboard & MoU Renewal Pipeline',
    category: 'College',
    frequency: 'Weekly',
    generatedDate: '2026-09-23T09:00:00Z',
    nextScheduled: '2026-09-30T00:00:00Z',
    format: 'Excel',
    fileSize: '3.2 MB',
    recipients: ['placement.desk@globalquesttechnologies.com', 'hr.director@globalquesttechnologies.com'],
    version: 'v4.5',
    isBoardConfidential: false,
  },
  {
    id: 'rpt-mgmt-04',
    title: 'Online Examination Proctoring & Integrity Telemetry Audit',
    category: 'Exam',
    frequency: 'Weekly',
    generatedDate: '2026-09-22T14:15:00Z',
    nextScheduled: '2026-09-29T00:00:00Z',
    format: 'PDF',
    fileSize: '6.1 MB',
    recipients: ['tech.dean@globalquesttechnologies.com', 'compliance@globalquesttechnologies.com'],
    version: 'v1.8',
    isBoardConfidential: true,
  },
  {
    id: 'rpt-mgmt-05',
    title: 'Offer Acceptance, Dropped Candidates & Batch Allocation Forecast',
    category: 'Offer',
    frequency: 'Weekly',
    generatedDate: '2026-09-24T16:00:00Z',
    nextScheduled: '2026-10-01T00:00:00Z',
    format: 'PDF',
    fileSize: '2.9 MB',
    recipients: ['admission@globalquesttechnologies.com', 'hr.leads@globalquesttechnologies.com'],
    version: 'v2.4',
    isBoardConfidential: false,
  },
  {
    id: 'rpt-mgmt-06',
    title: 'HR Executive Productivity, Call Logs & Meeting Conversion Report',
    category: 'HR',
    frequency: 'Weekly',
    generatedDate: '2026-09-21T18:00:00Z',
    nextScheduled: '2026-09-28T00:00:00Z',
    format: 'CSV',
    fileSize: '1.8 MB',
    recipients: ['hr.ops@globalquesttechnologies.com'],
    version: 'v5.0',
    isBoardConfidential: false,
  },
];

// =========================================================================
// 7. ENTERPRISE AUDIT LOGS FOR MANAGEMENT GOVERNANCE
// =========================================================================
export const MANAGEMENT_AUDIT_LOGS: ManagementAuditEntry[] = [
  {
    id: 'aud-001',
    timestamp: '2026-09-25T04:12:30Z',
    user: 'G.R Narendra Reddy',
    role: 'super_admin',
    module: 'CSR Drive Engine',
    action: 'Phase Advance',
    oldValue: 'Phase 7: Assessment Execution',
    newValue: 'Phase 8: Evaluation & Shortlisting',
    ipAddress: '115.112.82.14',
    browser: 'Chrome 128 / Windows 11 Pro',
    device: 'ThinkPad P16s (Bengaluru HQ)',
    location: 'Bengaluru, Karnataka',
    severity: 'info',
  },
  {
    id: 'aud-002',
    timestamp: '2026-09-25T03:45:10Z',
    user: 'Kiran',
    role: 'csr_manager',
    module: 'Institutional MoU',
    action: 'College Confirmation Approved',
    oldValue: 'Status: Pending Review',
    newValue: 'Status: Confirmed (MoU Executed)',
    ipAddress: '115.112.82.19',
    browser: 'Firefox 129 / macOS Sequoia',
    device: 'MacBook Pro M3 Max',
    location: 'Bengaluru, Karnataka',
    severity: 'info',
  },
  {
    id: 'aud-003',
    timestamp: '2026-09-24T22:15:00Z',
    user: 'System Cron Engine',
    role: 'super_admin',
    module: 'Offer Expiry Engine',
    action: 'Auto-Revoke 12 Unaccepted Offers',
    oldValue: 'Validity: 30-Aug-2026',
    newValue: 'Status: Expired (Waitlist released)',
    ipAddress: '10.0.4.12 (Internal VPC)',
    browser: 'Node.js Automated Worker v22',
    device: 'AWS ap-south-1 Server',
    location: 'Mumbai Cloud Data Center',
    severity: 'warning',
  },
  {
    id: 'aud-004',
    timestamp: '2026-09-24T18:20:45Z',
    user: 'Hitha, Kusuma',
    role: 'hr',
    module: 'Interview Evaluation',
    action: 'Student Selected',
    oldValue: 'Interview Status: In Progress',
    newValue: 'Result: Selected (Rating: 4.8/5.0)',
    ipAddress: '106.51.24.89',
    browser: 'Edge 128 / Windows 11',
    device: 'Dell Latitude 7440',
    location: 'Bengaluru, Karnataka',
    severity: 'info',
  },
  {
    id: 'aud-005',
    timestamp: '2026-09-24T15:10:12Z',
    user: 'Director GQT',
    role: 'management',
    module: 'Executive BI',
    action: 'Quarterly Board Audit Deck Exported',
    oldValue: 'None',
    newValue: 'Export Format: Signed PDF',
    ipAddress: '122.172.84.102',
    browser: 'Safari 18 / iPadOS',
    device: 'iPad Pro M4 (Executive Suite)',
    location: 'Bengaluru, Karnataka',
    severity: 'info',
  },
  {
    id: 'aud-006',
    timestamp: '2026-09-24T11:05:00Z',
    user: 'Security Guard Engine',
    role: 'super_admin',
    module: 'Authentication Gateway',
    action: 'Multiple Failed Login Throttled',
    oldValue: 'Attempts: 4',
    newValue: 'IP Temporarily Quarantined (15m)',
    ipAddress: '45.143.201.88',
    browser: 'Python Requests / Unknown Client',
    device: 'Unknown Client',
    location: 'Foreign Proxy (Throttled)',
    severity: 'critical',
  },
];

// =========================================================================
// 8. REALTIME ACTIVITY CENTER STREAM (LIVE OPERATIONS FEED)
// =========================================================================
export const MANAGEMENT_ACTIVITY_FEED: ManagementActivityFeedItem[] = [
  {
    id: 'act-001',
    timestamp: 'Just now',
    eventType: 'Offer Accepted',
    title: 'Aditi Rao accepted Associate Software Engineer Offer',
    description: 'Signed offer letter GQT/OFFER/2026/001 uploaded and confirmed for Full Stack Java Cloud batch.',
    entityType: 'Offer',
    entityId: 'off-001',
    actor: 'Aditi Rao (USN: 1RV22CS014)',
    actorRole: 'Student',
    statusBadge: 'Joining Confirmed',
  },
  {
    id: 'act-002',
    timestamp: '3 mins ago',
    eventType: 'Exam Submitted',
    title: 'B.M.S. College of Engineering Slot-2 Assessment Finalized',
    description: '142 candidates finished with 0 browser tab-switch infractions flagged by AI proctor.',
    entityType: 'Drive',
    entityId: 'drv-001',
    actor: 'AI Examination Engine',
    actorRole: 'System',
    statusBadge: 'Integrity 100%',
  },
  {
    id: 'act-003',
    timestamp: '12 mins ago',
    eventType: 'Interview Completed',
    title: 'Hitha Kusuma finalized Interview for Bharath Royal',
    description: 'Candidate scored 4.9/5 in Data Structures and Agentic System Prompting. Recommended for Select.',
    entityType: 'Interview',
    entityId: 'int-045',
    actor: 'Hitha, Kusuma',
    actorRole: 'HR Executive',
    statusBadge: 'Selected',
  },
  {
    id: 'act-004',
    timestamp: '25 mins ago',
    eventType: 'College Added',
    title: 'Basaveshwar Engineering College Bagalkote MoU Confirmed',
    description: 'Autonomous College signed CSR charter for 480 eligible 2026 passing out batch students.',
    entityType: 'College',
    entityId: 'col-013',
    actor: 'Kiran',
    actorRole: 'CSR Manager',
    statusBadge: 'MoU Active',
  },
  {
    id: 'act-005',
    timestamp: '42 mins ago',
    eventType: 'Student Registered',
    title: 'Surge in registrations from Dakshina Kannada coastal cluster',
    description: '95 new candidates registered for St. Joseph and Sahyadri College Drive within 1 hour.',
    entityType: 'Student',
    entityId: 'stu-bulk',
    actor: 'Public Student Portal',
    actorRole: 'Student',
    statusBadge: 'Verified',
  },
  {
    id: 'act-006',
    timestamp: '1 hour ago',
    eventType: 'Drive Published',
    title: 'North Karnataka Engineering Uplift Drive 2026 is LIVE',
    description: 'Published across Belagavi, Dharwad, Bagalkote & Kalaburagi districts covering 42 institutions.',
    entityType: 'Drive',
    entityId: 'drv-nk-02',
    actor: 'G.R Narendra Reddy',
    actorRole: 'Super Admin',
    statusBadge: 'Live Drive',
  },
  {
    id: 'act-007',
    timestamp: '2 hours ago',
    eventType: 'Escalation Missed',
    title: 'Follow-up missed for PDA College of Engineering TPO',
    description: 'Auto-escalated to CSR Operations Lead after 24-hour threshold exceeded.',
    entityType: 'System',
    entityId: 'esc-009',
    actor: 'Escalation Guard',
    actorRole: 'System',
    statusBadge: 'Escalated',
  },
];

// =========================================================================
// 9. AUTOMATED EXECUTIVE INSIGHTS PANEL (DIRECTOR BRIEFING)
// =========================================================================
export const MANAGEMENT_EXECUTIVE_INSIGHTS: ExecutiveInsightsItem[] = [
  {
    id: 'ins-01',
    type: 'positive',
    title: 'Top Performing District',
    description: 'Bengaluru Urban leads with 1,140 selections (25.8% selection rate) and a 91.7% offer acceptance ratio across 38 colleges.',
    metric: '1,140 Placed',
    tag: 'Placement Champion',
    timestamp: 'Today, 08:30 AM',
  },
  {
    id: 'ins-02',
    type: 'positive',
    title: 'Top Performing Institution',
    description: 'R.V. College of Engineering (RVCE) achieved the highest conversion with 273 final selections from 840 registrations.',
    metric: '32.5% Rate',
    tag: 'Tier-1 Benchmark',
    timestamp: 'Today, 08:30 AM',
  },
  {
    id: 'ins-03',
    type: 'positive',
    title: 'Top Performing HR Executive',
    description: 'Hitha Kusuma has conducted 885 interviews with a 94.2% offer acceptance rate and exceptional 1.4-hour avg turnaround time.',
    metric: '512 Selected',
    tag: 'HR Productivity',
    timestamp: 'Today, 08:30 AM',
  },
  {
    id: 'ins-04',
    type: 'warning',
    title: 'Lowest Registration District',
    description: 'Yadgir has only 120 registered candidates across 1 institution. Recommended to dispatch outreach van and engage TPO directly.',
    metric: '120 Reg',
    tag: 'Outreach Alert',
    timestamp: 'Today, 08:30 AM',
  },
  {
    id: 'ins-05',
    type: 'alert',
    title: 'Upcoming Offer Expiry Notice',
    description: '48 offer letters dispatched to Tier-2 engineering candidates will expire in the next 72 hours if acceptance is not completed.',
    metric: '48 Expiring',
    tag: 'Follow-Up Urgency',
    timestamp: 'Today, 08:30 AM',
  },
  {
    id: 'ins-06',
    type: 'metric',
    title: 'Pending Admission Verification',
    description: '64 accepted candidates await final 8th-semester mark-sheet & USN document verification by the Central Admission Cell.',
    metric: '64 Pending',
    tag: 'Admission Queue',
    timestamp: 'Today, 08:30 AM',
  },
];
