# Generated by Django 6.1.1 on 2026-09-28 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('tier', models.CharField(default='Tier-2', max_length=10)),
                ('mou_signed', models.BooleanField(default=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(max_length=100)),
                ('graduation_year', models.PositiveIntegerField(default=2026)),
                ('cgpa', models.DecimalField(decimal_places=2, default=7.5, max_digits=4)),
                ('tenth_percentage', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('twelfth_percentage', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('hall_ticket_number', models.CharField(blank=True, max_length=50, null=True)),
                ('current_round', models.CharField(default='Aptitude Assessment', max_length=50)),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Eligible', 'Eligible'), ('Assessment_Pending', 'Assessment Pending'), ('Qualified', 'Qualified Cutoff'), ('Interview_Scheduled', 'Interview Scheduled'), ('Selected', 'Selected / Offered'), ('Rejected', 'Rejected'), ('Placed', 'Placed & Joined')], default='Registered', max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.college')),
            ],
        ),
    ]
