# Generated by Django 6.1.1 on 2026-09-28 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drives', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_code', models.CharField(max_length=50, unique=True)),
                ('role_title', models.CharField(default='Graduate Software Engineer', max_length=150)),
                ('ctc', models.DecimalField(decimal_places=2, default=650000.0, max_digits=10)),
                ('joining_location', models.CharField(default='Bengaluru, Karnataka', max_length=150)),
                ('joining_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued to Candidate'), ('Accepted', 'Accepted & Signed'), ('Declined', 'Declined by Candidate'), ('Revoked', 'Revoked')], default='Issued', max_length=20)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('drive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drives.csrdrive')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='students.student')),
            ],
        ),
    ]
