import {
  WhatsAppMessageRecord,
  WhatsAppGroupRecord,
  WhatsAppTemplate,
  EmailMessageRecord,
  EmailTemplate,
  AnnouncementRecord,
  CallLogRecord,
  MeetingRecord,
  FollowUpReminder,
  CommunicationTimelineItem
} from "@/types";

export const INITIAL_WHATSAPP_TEMPLATES: WhatsAppTemplate[] = [
  {
    id: "wa-tmpl-01",
    name: "gqt_drive_registration_confirmed_v1",
    category: "Student Registration",
    content: "Hi {{student_name}}! 🎉 Your registration for the {{drive_name}} at {{college_name}} has been verified. Your Assessment Exam is scheduled on {{exam_date}}.",
    placeholders: ["student_name", "drive_name", "college_name", "exam_date"],
  },
  {
    id: "wa-tmpl-02",
    name: "gqt_exam_reminder_24h_v2",
    category: "Exam Reminder",
    content: "Dear {{student_name}}, reminder: Your GQT Online Assessment begins tomorrow at {{exam_time}}. Please ensure Chrome browser on desktop with webcam access.",
    placeholders: ["student_name", "exam_time"],
  },
  {
    id: "wa-tmpl-03",
    name: "gqt_interview_slot_invitation_v1",
    category: "Interview Schedule",
    content: "Congratulations {{student_name}}! You qualified in the GQT CSR Assessment. Your Technical Interview is scheduled on {{interview_date}} at {{interview_time}}.",
    placeholders: ["student_name", "interview_date", "interview_time"],
  },
  {
    id: "wa-tmpl-04",
    name: "gqt_offer_letter_issued_v1",
    category: "Offer Release",
    content: "Hearty Congratulations {{student_name}}! 🌟 Your Official Letter of Intent (LOI) {{offer_number}} has been issued. Preview & digitally accept in your student portal.",
    placeholders: ["student_name", "offer_number"],
  },
  {
    id: "wa-tmpl-05",
    name: "gqt_placement_officer_drive_reminder_v1",
    category: "Drive Confirmation",
    content: "Respected {{contact_person}}, GQT CSR Drive preparations for {{college_name}} are live. Group link created. Total student registrations: {{student_count}}.",
    placeholders: ["contact_person", "college_name", "student_count"],
  },
];

export const INITIAL_WHATSAPP_GROUPS: WhatsAppGroupRecord[] = [
  {
    id: "wag-001",
    groupName: "R.V. College of Engineering + GQT + 2026-27",
    groupId: "120363024891102934@g.us",
    inviteLink: "https://chat.whatsapp.com/GQT-RVCE-2026-CSR",
    createdDate: "2026-09-10",
    driveId: "drv-001",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    collegeId: "col-rvce",
    collegeName: "R.V. College of Engineering (RVCE)",
    hrId: "usr-hr-01",
    hrName: "Priya Nair",
    ptoId: "usr-pto-01",
    ptoName: "Prof. Chandrasekhar",
    facultyNames: ["Dr. Sunitha Verma (CS)", "Prof. Rajesh K. (IS)"],
    status: "Active",
    membersCount: 48,
  },
  {
    id: "wag-002",
    groupName: "BMS College of Engineering + GQT + 2026-27",
    groupId: "120363024891102935@g.us",
    inviteLink: "https://chat.whatsapp.com/GQT-BMSCE-2026-CSR",
    createdDate: "2026-09-12",
    driveId: "drv-001",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    collegeId: "col-bmsce",
    collegeName: "B.M.S. College of Engineering (BMSCE)",
    hrId: "usr-hr-02",
    hrName: "Arun Menon",
    ptoId: "usr-pto-02",
    ptoName: "Dr. Muralidhara",
    facultyNames: ["Prof. Kavitha S. (AI)", "Prof. Anand (ECE)"],
    status: "Active",
    membersCount: 52,
  },
  {
    id: "wag-003",
    groupName: "Ramaiah Institute of Technology + GQT + 2026-27",
    groupId: "120363024891102936@g.us",
    inviteLink: "https://chat.whatsapp.com/GQT-MSRIT-2026-CSR",
    createdDate: "2026-09-14",
    driveId: "drv-001",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    collegeId: "col-msrit",
    collegeName: "Ramaiah Institute of Technology (MSRIT)",
    hrId: "usr-hr-01",
    hrName: "Priya Nair",
    ptoId: "usr-pto-03",
    ptoName: "Prof. Gururaj",
    facultyNames: ["Dr. Preethi (CSE)"],
    status: "Active",
    membersCount: 44,
  },
];

export const INITIAL_WHATSAPP_MESSAGES: WhatsAppMessageRecord[] = [
  {
    id: "wam-001",
    recipientPhone: "+91 98450 11992",
    recipientName: "Aditya V. Kashyap",
    role: "Student",
    templateName: "gqt_offer_letter_issued_v1",
    content: "Hearty Congratulations Aditya V. Kashyap! 🌟 Your Official Letter of Intent (LOI) GQT/OFFER/2026/001 has been issued. Preview & digitally accept in your student portal.",
    status: "Read",
    retryCount: 0,
    timestamp: "2026-09-24T10:30:00Z",
    deliveredAt: "2026-09-24T10:30:12Z",
    readAt: "2026-09-24T10:35:40Z",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    collegeName: "R.V. College of Engineering (RVCE)",
  },
  {
    id: "wam-002",
    recipientPhone: "+91 98451 22334",
    recipientName: "Sneha Ramachandra Rao",
    role: "Student",
    templateName: "gqt_offer_letter_issued_v1",
    content: "Hearty Congratulations Sneha Ramachandra Rao! 🌟 Your Official Letter of Intent (LOI) GQT/OFFER/2026/002 has been issued. Preview & digitally accept in your student portal.",
    status: "Delivered",
    retryCount: 0,
    timestamp: "2026-09-24T11:15:00Z",
    deliveredAt: "2026-09-24T11:15:15Z",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    collegeName: "B.M.S. College of Engineering (BMSCE)",
  },
  {
    id: "wam-003",
    recipientPhone: "+91 98452 33445",
    recipientName: "Karthik Srinivas",
    role: "Student",
    templateName: "gqt_offer_letter_issued_v1",
    content: "Hearty Congratulations Karthik Srinivas! 🌟 Your Official Letter of Intent (LOI) GQT/OFFER/2026/003 has been issued. Preview & digitally accept in your student portal.",
    status: "Sent",
    retryCount: 0,
    timestamp: "2026-09-24T12:00:00Z",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    collegeName: "Ramaiah Institute of Technology (MSRIT)",
  },
  {
    id: "wam-004",
    recipientPhone: "+91 98450 99881",
    recipientName: "Rohan Patil",
    role: "Student",
    templateName: "gqt_exam_reminder_24h_v2",
    content: "Dear Rohan, reminder: Your GQT Online Assessment begins tomorrow at 10:00 AM IST. Please ensure Chrome browser on desktop with webcam access.",
    status: "Failed",
    retryCount: 2,
    errorLog: "Error 131026: Message undeliverable - phone switched off or out of network area.",
    timestamp: "2026-09-24T09:00:00Z",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    collegeName: "KLE Tech University",
  },
];

export const INITIAL_EMAIL_TEMPLATES: EmailTemplate[] = [
  {
    id: "em-tmpl-01",
    name: "Corporate LOI & Appointment Notification",
    subject: "Global Quest Technologies — Official Letter of Intent (LOI): {{offer_number}}",
    category: "Offer Letter",
    placeholders: ["student_name", "offer_number", "course_name", "joining_date", "center_location"],
    lastModifiedBy: "Director G.R. Narendra Reddy",
    updatedAt: "2026-09-22T10:00:00Z",
    htmlContent: `
<!DOCTYPE html>
<html>
<body style="font-family: Arial, sans-serif; background: #f8fafc; padding: 20px;">
  <div style="max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 16px; border: 1px solid #e2e8f0; overflow: hidden;">
    <div style="background: linear-gradient(135deg, #001B4D, #005BBB); padding: 30px; text-align: center; color: white;">
      <h1 style="margin: 0; font-size: 24px;">GLOBAL QUEST TECHNOLOGIES</h1>
      <p style="margin: 5px 0 0 0; font-size: 12px; letter-spacing: 1px;">TRAINING • INNOVATION • PLACEMENT SERVICES</p>
    </div>
    <div style="padding: 30px; color: #1e293b; line-height: 1.6;">
      <h2>Congratulations {{student_name}}!</h2>
      <p>We are delighted to issue your official Letter of Intent (LOI) <strong>{{offer_number}}</strong> under the Global Quest Technologies CSR Engineering Uplift Initiative.</p>
      <div style="background: #f1f5f9; padding: 15px; border-radius: 12px; margin: 20px 0;">
        <p style="margin: 5px 0;"><strong>Role Track:</strong> {{course_name}}</p>
        <p style="margin: 5px 0;"><strong>Date of Joining:</strong> {{joining_date}}</p>
        <p style="margin: 5px 0;"><strong>Reporting Venue:</strong> {{center_location}}</p>
        <p style="margin: 5px 0;"><strong>Sponsorship:</strong> 100% GQT CSR Subsidized (Zero Bond Policy)</p>
      </div>
      <p>Please log in to your Student Portal to review your digital document and submit your electronic acceptance consent.</p>
    </div>
  </div>
</body>
</html>`,
  },
  {
    id: "em-tmpl-02",
    name: "Assessment Schedule & Proctor Guidelines",
    subject: "GQT Assessment Exam Invitation — {{drive_name}}",
    category: "Exam",
    placeholders: ["student_name", "drive_name", "exam_date", "exam_time", "login_url"],
    lastModifiedBy: "Kiran (CSR Manager)",
    updatedAt: "2026-09-20T14:30:00Z",
    htmlContent: `
<!DOCTYPE html>
<html>
<body style="font-family: Arial, sans-serif; background: #f8fafc; padding: 20px;">
  <div style="max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 16px; border: 1px solid #e2e8f0; overflow: hidden;">
    <div style="background: #001B4D; padding: 25px; color: white;">
      <h2 style="margin: 0;">Online Examination Notice</h2>
    </div>
    <div style="padding: 25px; color: #334155;">
      <p>Dear {{student_name}}, your online test for {{drive_name}} is confirmed for <strong>{{exam_date}} at {{exam_time}}</strong>.</p>
      <p>System requirements: Chrome browser, functional webcam, stable internet connection.</p>
    </div>
  </div>
</body>
</html>`,
  },
];

export const INITIAL_EMAIL_MESSAGES: EmailMessageRecord[] = [
  {
    id: "emm-001",
    recipientEmail: "aditya.kashyap@rvce.edu.in",
    recipientName: "Aditya V. Kashyap",
    subject: "Global Quest Technologies — Official Letter of Intent (LOI): GQT/OFFER/2026/001",
    templateName: "Corporate LOI & Appointment Notification",
    contentHtml: "<p>LOI dispatched for Aditya V. Kashyap</p>",
    status: "Opened",
    timestamp: "2026-09-24T10:30:00Z",
    openedAt: "2026-09-24T10:45:00Z",
    clickedAt: "2026-09-24T10:47:00Z",
    retryCount: 0,
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    collegeName: "R.V. College of Engineering (RVCE)",
  },
  {
    id: "emm-002",
    recipientEmail: "sneha.rao@bmsce.ac.in",
    recipientName: "Sneha Ramachandra Rao",
    subject: "Global Quest Technologies — Official Letter of Intent (LOI): GQT/OFFER/2026/002",
    templateName: "Corporate LOI & Appointment Notification",
    contentHtml: "<p>LOI dispatched for Sneha Rao</p>",
    status: "Delivered",
    timestamp: "2026-09-24T11:15:00Z",
    retryCount: 0,
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    collegeName: "B.M.S. College of Engineering (BMSCE)",
  },
  {
    id: "emm-003",
    recipientEmail: "placement@rvce.edu.in",
    recipientName: "Prof. Chandrasekhar (PTO)",
    subject: "GQT CSR Drive 2026 — Assessment Qualification Roster & Interview Slots",
    templateName: "Placement Officer Drive Report",
    contentHtml: "<p>RVCE Qualified candidates list attached.</p>",
    status: "Clicked",
    timestamp: "2026-09-23T16:00:00Z",
    openedAt: "2026-09-23T16:10:00Z",
    clickedAt: "2026-09-23T16:12:00Z",
    retryCount: 0,
    collegeName: "R.V. College of Engineering (RVCE)",
  },
  {
    id: "emm-004",
    recipientEmail: "invalid-email@notfoundcollege.edu.in",
    recipientName: "Student Alpha",
    subject: "Exam Schedule Notice",
    templateName: "Assessment Schedule & Proctor Guidelines",
    contentHtml: "<p>Test notification</p>",
    status: "Bounced",
    timestamp: "2026-09-23T18:00:00Z",
    retryCount: 1,
    errorLog: "550 5.1.1 User unknown / Host mailbox not found",
  },
];

export const INITIAL_ANNOUNCEMENTS: AnnouncementRecord[] = [
  {
    id: "anc-001",
    title: "Official Batch Alpha Onboarding & Reporting Guidelines 2026",
    description: "All students who accepted their GQT CSR Letters of Intent are requested to review reporting dates, hostel options, and center transport schedules.",
    contentHtml: "Full campus guidelines for Whitefield Learning Center, Bangalore.",
    targetAudience: ["All Students", "Admission Team"],
    channels: ["Dashboard", "Email", "WhatsApp"],
    priority: "High",
    publishedAt: "2026-09-24T09:00:00Z",
    isPinned: true,
    authorName: "G.R. Narendra Reddy",
    authorRole: "Director - CSR",
    viewsCount: 384,
  },
  {
    id: "anc-002",
    title: "Round 2 Technical Interview Slots Published for Tier-2 Colleges",
    description: "Shortlisted candidates from GIT Belagavi and NMAMIT Nitte can now view their panel timings and Google Meet links in the student portal.",
    targetAudience: ["Specific Colleges", "HR"],
    collegeIds: ["col-git", "col-nmamit"],
    channels: ["Dashboard", "WhatsApp"],
    priority: "Medium",
    publishedAt: "2026-09-23T14:00:00Z",
    isPinned: false,
    authorName: "Priya Nair",
    authorRole: "Senior HR Lead",
    viewsCount: 215,
  },
  {
    id: "anc-003",
    title: "Placement Officers Coordination Meeting — Karnataka Engineering Phase",
    description: "Executive virtual sync on Friday 4:00 PM IST with Principals and Training & Placement Directors regarding CSR scholarship quotas.",
    targetAudience: ["Placement Officers", "Faculty"],
    channels: ["Dashboard", "Email"],
    priority: "Critical",
    publishedAt: "2026-09-22T11:00:00Z",
    isPinned: true,
    authorName: "Kiran",
    authorRole: "CSR Operations Manager",
    viewsCount: 78,
  },
];

export const INITIAL_CALL_LOGS: CallLogRecord[] = [
  {
    id: "cl-001",
    collegeId: "col-rvce",
    collegeName: "R.V. College of Engineering (RVCE)",
    contactPerson: "Prof. Chandrasekhar",
    contactPhone: "+91 98450 44556",
    contactRole: "Director of Training & Placement",
    callDate: "2026-09-24",
    startTime: "11:00 AM",
    endTime: "11:22 AM",
    durationSeconds: 1320,
    callType: "Outgoing",
    callStatus: "Connected",
    discussionSummary: "Discussed lab availability for 350 candidates during exam window. PTO confirmed computer center block 3 is reserved with power backup.",
    outcome: "MoU Agreed",
    nextFollowUpDate: "2026-09-28",
    priority: "High",
    notes: "Very supportive. Requested 100 extra student seats for Information Science branch.",
    loggedBy: "Priya Nair (HR)",
  },
  {
    id: "cl-002",
    collegeId: "col-bmsce",
    collegeName: "B.M.S. College of Engineering (BMSCE)",
    contactPerson: "Dr. Muralidhara",
    contactPhone: "+91 98451 55667",
    contactRole: "Placement Officer",
    callDate: "2026-09-24",
    startTime: "02:30 PM",
    endTime: "02:45 PM",
    durationSeconds: 900,
    callType: "Incoming",
    callStatus: "Connected",
    discussionSummary: "PTO inquired about offer letter release schedule for MCA candidates. Clarified that MCA interviews wrap up on Thursday.",
    outcome: "Follow-up Needed",
    nextFollowUpDate: "2026-09-27",
    priority: "Medium",
    loggedBy: "Arun Menon (HR)",
  },
  {
    id: "cl-003",
    collegeId: "col-msrit",
    collegeName: "Ramaiah Institute of Technology (MSRIT)",
    contactPerson: "Prof. Gururaj",
    contactPhone: "+91 98452 66778",
    contactRole: "Faculty Coordinator",
    callDate: "2026-09-23",
    startTime: "04:15 PM",
    endTime: "04:16 PM",
    durationSeconds: 45,
    callType: "Outgoing",
    callStatus: "Busy",
    discussionSummary: "Phone was busy. Left automated SMS and WhatsApp follow-up ping.",
    outcome: "Call Later",
    nextFollowUpDate: "2026-09-25",
    priority: "Urgent",
    loggedBy: "Priya Nair (HR)",
  },
];

export const INITIAL_MEETINGS: MeetingRecord[] = [
  {
    id: "mtg-001",
    title: "CSR Drive Alignment & Auditorium Setup Sync",
    collegeId: "col-rvce",
    collegeName: "R.V. College of Engineering (RVCE)",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    attendees: [
      { name: "Priya Nair", role: "HR Executive", email: "priya@gqtindia.com", attended: true },
      { name: "Prof. Chandrasekhar", role: "Placement Officer", email: "placement@rvce.edu.in", attended: true },
      { name: "Dr. Sunitha Verma", role: "Faculty Coordinator", email: "sunitha@rvce.edu.in", attended: true },
      { name: "Dr. K.N. Subramanya", role: "Principal", email: "principal@rvce.edu.in", attended: false },
    ],
    date: "2026-09-24",
    time: "03:00 PM - 04:00 PM",
    durationMinutes: 60,
    mode: "Hybrid",
    meetingLink: "https://meet.google.com/gqt-rvce-sync",
    venue: "Boardroom 2, Admin Block, RVCE Campus",
    agenda: "Finalize offline proctoring staff, student identity badge checks, and CSR banner placements.",
    minutesOfMeeting: [
      "Auditorium sound system and 400 ethernet terminals approved.",
      "Faculty coordinators will oversee student queue management.",
      "GQT banners and registration kiosks to be set up by 8:00 AM on drive day.",
    ],
    status: "Completed",
  },
  {
    id: "mtg-002",
    title: "Regional Hubballi Colleges Online Onboarding Sync",
    collegeId: "col-kletech",
    collegeName: "KLE Technological University, Hubballi",
    driveName: "North Karnataka Tier-2 Engineering Drive",
    attendees: [
      { name: "Kiran", role: "CSR Operations Manager", email: "kiran@gqtindia.com" },
      { name: "Arun Menon", role: "HR Executive", email: "arun@gqtindia.com" },
      { name: "Dr. Ashok Patil", role: "Dean Placement", email: "placement@kletech.ac.in" },
    ],
    date: "2026-09-26",
    time: "11:00 AM - 12:00 PM",
    durationMinutes: 60,
    mode: "Online",
    meetingLink: "https://meet.google.com/gqt-kletech-hub",
    agenda: "Review candidate registration numbers, verify student VTU eligibility, and configure test papers.",
    status: "Scheduled",
  },
];

export const INITIAL_FOLLOW_UPS: FollowUpReminder[] = [
  {
    id: "fu-001",
    collegeId: "col-rvce",
    collegeName: "R.V. College of Engineering (RVCE)",
    contactPerson: "Prof. Chandrasekhar",
    contactPhone: "+91 98450 44556",
    scheduledFor: "2026-09-25",
    dueCategory: "Today",
    purpose: "Collect signed institutional MoU and confirm 400 candidate exam slots.",
    assignedTo: "Priya Nair",
    priority: "Urgent",
    status: "Pending",
    notes: "Principal approval received in email; need physical signature scan.",
    emailReminderSent: true,
    whatsappReminderSent: true,
  },
  {
    id: "fu-002",
    collegeId: "col-bmsce",
    collegeName: "B.M.S. College of Engineering (BMSCE)",
    contactPerson: "Dr. Muralidhara",
    contactPhone: "+91 98451 55667",
    scheduledFor: "2026-09-26",
    dueCategory: "Upcoming",
    purpose: "Review shortlisting criteria for AI & Data Analytics candidates.",
    assignedTo: "Arun Menon",
    priority: "High",
    status: "Pending",
    emailReminderSent: false,
    whatsappReminderSent: true,
  },
  {
    id: "fu-003",
    collegeId: "col-msrit",
    collegeName: "Ramaiah Institute of Technology (MSRIT)",
    contactPerson: "Prof. Gururaj",
    contactPhone: "+91 98452 66778",
    scheduledFor: "2026-09-23",
    dueCategory: "Overdue",
    purpose: "Unanswered follow-up regarding missing MCA student registration list.",
    assignedTo: "Priya Nair",
    priority: "Urgent",
    status: "Pending",
    notes: "Escalated to CSR Manager Kiran automatically due to 48hr delay.",
    emailReminderSent: true,
    whatsappReminderSent: true,
  },
  {
    id: "fu-004",
    collegeId: "col-git",
    collegeName: "KLS Gogte Institute of Technology (GIT), Belagavi",
    contactPerson: "Dr. Kulkarni",
    contactPhone: "+91 98453 77889",
    scheduledFor: "2026-09-24",
    dueCategory: "Completed",
    purpose: "Conducted virtual orientation call for 280 eligible engineers.",
    assignedTo: "Divya H",
    priority: "Medium",
    status: "Completed",
    emailReminderSent: true,
    whatsappReminderSent: true,
  },
];

export const INITIAL_COMMUNICATION_TIMELINE: CommunicationTimelineItem[] = [
  {
    id: "ctl-001",
    collegeId: "col-rvce",
    collegeName: "R.V. College of Engineering (RVCE)",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    type: "Call",
    title: "Outbound Call with Director Placement",
    summary: "Confirmed computer lab block 3 reservation with 350 terminals for upcoming assessment.",
    timestamp: "2026-09-24 11:22 AM",
    performedBy: "Priya Nair (Senior HR)",
    statusBadge: "Connected (22 mins)",
  },
  {
    id: "ctl-002",
    collegeId: "col-rvce",
    collegeName: "R.V. College of Engineering (RVCE)",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    type: "WhatsApp",
    title: "Official WhatsApp Group Created",
    summary: "Automated group 'R.V. College of Engineering + GQT + 2026-27' initialized with 48 members.",
    timestamp: "2026-09-24 11:30 AM",
    performedBy: "WhatsApp Business Engine",
    statusBadge: "Group Active",
  },
  {
    id: "ctl-003",
    collegeId: "col-rvce",
    collegeName: "R.V. College of Engineering (RVCE)",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    type: "Email",
    title: "Dispatched Official LOIs to 42 Selected Candidates",
    summary: "Cryptographically signed appointment letters sent via multi-channel notification engine.",
    timestamp: "2026-09-24 10:30 AM",
    performedBy: "Director G.R. Narendra Reddy",
    statusBadge: "42 Delivered",
  },
  {
    id: "ctl-004",
    collegeId: "col-rvce",
    collegeName: "R.V. College of Engineering (RVCE)",
    driveName: "Karnataka State-wide CSR Engineering Drive 2026",
    type: "Meeting",
    title: "Hybrid Boardroom Coordination Sync",
    summary: "Discussed offline student badge screening, entrance gate kiosks, and faculty invigilators.",
    timestamp: "2026-09-24 04:00 PM",
    performedBy: "Priya Nair & Dr. Sunitha Verma",
    statusBadge: "MoM Recorded",
  },
  {
    id: "ctl-005",
    collegeId: "col-msrit",
    collegeName: "Ramaiah Institute of Technology (MSRIT)",
    type: "Reminder",
    title: "Automated Escalation Alert",
    summary: "Follow-up regarding MCA student records overdue by 24h. Escalated to CSR Manager & Admin.",
    timestamp: "2026-09-24 08:00 AM",
    performedBy: "Automated Escalation Engine",
    statusBadge: "Escalated",
  },
];
